import React from 'react';
import styles from './Future.module.css'
import Footer from '../components/Footer/Footer';

function Future() {
  return (
    <>
    <main className={styles.container}>
        <div className={styles.box}>
        <h3 className={styles.preface}>Future Directions</h3>
      <p className={styles.content}>
      It is simultaneously one of the most hopeful and depressing facts about the state of modern medicine that the most powerful and demonstrably effective interventions we have at our disposal are almost entirely non-technological. Periodic fasting, sufficient exercise, quality sleep and nutrition are well recognised as the fundamental pillars of good health, the most consequential levers for cultivating wellness and staving off disease. This is hopeful, in that it means the tools required to ameliorate the current public health crisis are, by and large, available to us all. It is depressing, however, in that it means for all our investment in biomedical science and technology, all the promises of diet pills and superlative genetic therapies, we are yet to develop technologies as effective as, among other things, getting a good night sleep. This fact provokes two types of response. The first is that of the medical nihilists. Given the relative lack of success we’ve had developing effective ‘modern’ medical interventions, we should abandon the pursuit entirely - or at least scale back our investment considerably - and instead, invest in the kinds of preventative modalities - such as the above - so that we may avoid the need for more technological solutions in the first place. We tried the technology thing and it failed, the nihilists argue, so let’s go back to nature, let food be thy medicine etc. The second response, on the other hand, the broadly optimistic position, is that we simply haven’t tried hard enough, or that reductionism was a dead end and we should pursue a different approach, maybe a more ‘holistic’ systems-based approach à la the above. The two conclusions, I suggest, are not mutually exclusive. Indeed together they pave the path forward. 
<br></br><br></br>
The difference between the two perspectives are, much as anything, differences to do with temporality; that is, with the time frames in which we are thinking. From a pragmatic, short-term perspective, it’s hard to argue with the nihilists’ calls for a more ‘gentle’ - or anti-interventionist - medicine. The majority of existing medical interventions are, as we saw, disconcertingly ineffective. Natural healing technologies such as quality nutrition and exercise, on the other hand, are comparatively far more efficacious, not to mention less costly and free of undesirable side effects. Therefore, it makes good sense to favour such ‘lifestyle’ medicines. Moreover, given its historical success, and given the fundamental significance of the environment in the human health equation, we should allocate more of our resources towards the public health side of things, and if it’s one or the other, less towards the strictly reductionist biomedical program. From cleaning up the environment of toxins/pollutants to improving the quality of our food and water supplies (subsidising real food and taxing sugar perhaps?), there is immense low-hanging fruit waiting to be picked. As in the 19th and 20th centuries, the greatest gains in human health in the 21st century, it appears almost certain, will come from efforts in the public health domain. 
<br></br><br></br>
From a wider vantage point, science and technology appear poised to play a more pivotal role than such environmental/lifestyle modifications. For if what we desire is exponential improvements in our health - an ability to intervene in our own bodily systems orders of magnitude beyond our present - it will unequivocally require ‘unnatural’ aids. Natural modalities, after all, have natural limits. Though they are powerful, they only move the needle so far. Irrespective of how dialled in we have our lifestyles, we cannot render ourselves wholly immune to cancer, for instance. Nor can we live beyond the order of 120 years, or gain an additional 100 IQ points. While there is an interesting conversation to be had concerning whether or not we should in fact desire such things, if we hold that we should (as I suggest we ought to), then it follows that we must employ the use of science and technology to the fullest extent possible. 
<br></br><br></br>
If what we are chasing is radical improvements to human health, we need science and technology. But as I just argued, science and technology has, to date, done very little for our health. So then what reason have we to be optimistic about its prospects moving forward? Why, in other words, should we expect the future to diverge from the past? The answer to this is manifold. Firstly, optimism is at least partially implied by the belief that reductionism is a flawed - certainly incomplete - methodology for understanding complex systems. Given how far we’ve taken reductionism in biology/medicine, imagine just how far we could go with a methodological framework that was actually well-suited to the investigation of complex phenomena. By pursuing non-reductive explanations, alongside reductionist/mechanistic ones, it seems highly plausible that we will make significant strides in understanding the emergent - yet equally fundamental - laws that govern life. With such an understanding, it seems equally plausible, will come a new and profound capacity for modulating the function of life, including our own. Moreover, by doing away with the disciplinary divide that currently hinders the study of all things, most of all complex things, we should expect an acceleration in our understanding to follow. 
<br></br><br></br>
There is even reason to suggest that such a shift is already well under way. The new field of computational systems biology (CSB), for instance, represents the merging of mathematical techniques, computer science and biology; a promising example of transdisciplinary investigation in action. The field of synthetic biology, moreover, bearing many similarities to CSB, also harnesses the application of engineering principles to the study (and ultimately construction) of biological systems. In contrast to more traditional sub-disciplines within biology, CSB and synthetic biology explicitly embrace emergence as a concept and are on the whole suspect of purely reductionist investigation. Although it has been questioned whether CSB and synthetic biology are fundamentally divergent from other biological research paradigms or whether they’re merely extensions of molecular biology, however you slice it, they represent philosophical progress of a kind. That synthetic biology has, in its very short history, already achieved considerable success is, if nothing else, proof of the epistemic value of its transdisciplinary approach and unique methodological framework.   
<br></br><br></br>


      </p>
      </div>
    </main>
    <Footer nextTitle="Prevention As Research Paradigm" nextPage="/prevention"/>
    </>
  );
}

export default Future;
