import React from 'react';
import styles from './DeadPhilosophy.module.css'

function DeadPhilosophy() {
  return (
    <main className={styles.container}>
        <div className={styles.box}>
        <h3 className={styles.preface}>Philosophy Is Dead, So What?</h3>
      <p className={styles.content}>
      One might ask, So what if philosophy has lost its relevancy? So what if it’s dead? Of course, that one might plausibly ask such a question in the first place is itself testament to the disconnect between modern life and the ideals of philosophy. For philosophy is at the absolute heart of the human project. In fact, they are one and the same. Humanity is, at its very core, a fundamentally philosophical undertaking. Contrary to its present reputation, philosophy is not some thing at the periphery of what we do, in a very real sense, it is all we do. <br></br><br></br>

All that’s required in order to appreciate the centrality of philosophy is to consider what an individual human life is, and what it is in the aggregate, that is civilisation. The individual experience and civilisation alike are expressions of human consciousness, human thought. Manifest mental material. You will remember that we defined philosophy earlier as the pursuit of Knowledge. And while Knowledge is an elusive, highly mysterious phenomenon, whatever it is, we know it consists of this very same material - ideas, values, beliefs etc. What distinguishes Knowledge from other forms of mental material is that the mental material that constitutes Knowledge bears some correspondence or symmetry with Reality.[ Acknowledge that correspondence theory of Knowledge is inadequate, there are holes in it. But it’s a good working, common sense definition. Pragmatism. ] Much to the postmodernists chagrin, it contains Truth. <br></br><br></br>

If we appreciate that philosophy is made of the same fundamental material as our lives and thus civilisation (and not only that it’s made of the same material, but that it’s concerned with the mining, analysis and architecture of it) an appreciation of its importance should naturally follow. At some level of abstraction, the central goal of the human project, individually and collectively, is to imbue our minds and the very structure of our world, with as much Knowledge, as much Truth, as possible. This is the positive function of philosophy. In addition to the embodiment of Knowledge, however, the role of philosophy is to expel, from our lives and the structure of our world, its opposite: ignorance, illusion, misunderstanding. This is the negative function of philosophy. Having ascribed philosophy this dual function, the state of our lives, and the state of our world, at any given time, can therefore be seen as a reflection of the state of philosophy.   <br></br><br></br>

*While physicalism might - it’s certainly possible - represent the ultimate metaphysical truth, it’s at least pragmatically useful, I suggest, to think of there being a mental - or simply ‘non-physical’ - substrate to the universe. For we cannot understand the world - nor our own lives - without taking into account the mental properties they apparently reflect. That is, the ideas, the values, the beliefs. What philosophy is, to my mind, is the science and engineering of this mental substrate. The way I see it, the philosopher is a kind of software engineer, only working at a much higher level of abstraction than machine code - indeed the level of society’s operating system.
<br></br><br></br>


Placing philosophy at the centre of the human project is, on one hand, to gratify the field by duly acknowledging its vital importance, and on the other, to place an enormous burden upon the enterprise’s shoulders. For if the state of things fundamentally reflects the state of philosophy, if the former isn’t up to scratch, it’s the latter that’s ultimately to blame. If things are any less than they could be, in other words, it’s the fault of philosophy. A rather heavy responsibility, if ever there was one.  
<br></br><br></br>
Philosophy, as I’ve defined it, is a sprawling enterprise. The Knowledge Project. My criticism, however, is aimed squarely at the formal discipline, academia, the ivory tower, philosophy as an institution. Due to the various dynamics, biases, prejudices and so forth at play within academia, philosophy has been perverted in various ways. That’s the claim, distilled. Why, though, if philosophy is this giant thing - the pursuit of knowledge - that spans the entire human project, should we care so much (if at all) whether the formal practice of philosophy is a little banged up? After all, philosophy is everything. Philosophy is science, philosophy is art, philosophy is knowledge as embodied in Culture across the board. What we refer to as “philosophy” is merely one branch of the knowledge project, a small group of individuals that are particularly intentional about the pursuit of knowledge and focused in terms of the kind of knowledge - the types of questions - they’re interested in pursuing. As a portion of philosophy as a whole, the formal practice of philosophy is an almost insignificant sliver. Why, then, should a claim re the state of philosophy rest on a claim simply about the state of the formal discipline? “Philosophers” may have lost touch with the realities of Reality, one might argue, but so what, that’s what People are for. We no longer seek instruction as to how to live, or what this is all is, from Philosophers but instead counsel celebrities, podcasters, entrepreneurs, artists, athletes, scientists. Living embodiments (we hope) of practical wisdom. The most influential philosophers on the planet are no longer formally trained wisdom seekers, but rather the Tim Ferris’s and Joe Rogan’s of the world. Philosophy isn’t dead, it’s simply no longer where or what it used to be. Kanye’s the new Nietzsche.[ In my not so humble opinion, Kanye is twice the artist / philosopher Nietzsche was. At least when it comes to Kanye, his talent is unquestionable. What he is good, he is unambiguously so at. That is more than can be said for Nietzsche. ] What’s wrong, if anything, with that? <br></br><br></br>

On one hand, there’s nothing wrong. For there is nothing intrinsically special or superior about knowledge produced within a formal, academic, institutional context. Knowledge is Knowledge, whether the universe instantiates it in the form of a leather bound book or a 16 bar verse. It also makes sense that practical philosophy should be done not by theoreticians, those who live primarily in the polished realm of the abstract, but rather those grounded in the messy world of experience. That is, we should seek guidance as to how to live, not only from those who have theorised, from first principles, how best to, but from those who have demonstrated their ability to embody the knowledge necessary to live well. Those that have walked the path successfully are of more use, in many instances, than those who have simply studied the path extensively. On the other hand, however, the decay of formal, “serious” philosophy is in fact problematic on a number of levels. For one, even though there is very little engagement between the average citizen and formal philosophy, philosophers both past and present - as society’s intellectual elite - nevertheless continue to wield disproportionate influence over the collective consciousness. Not through direct engagement, but through its place in the hierarchy of our cultural infrastructure. Those who are serious about thinking, serious about Knowledge, naturally and invariably read the “serious” philosophers. Since the kind of cats that gravitate towards serious anything are those most likely to occupy positions of intellectual authority, by virtue of their authority, they wield disproportionate influence themselves. In other words, there is a kind of ‘trickle down’ effect at play. Very few people mess with philosophy, but those who do spread it wide and far. Thus whatever problems are at play within philosophy as an institution are not confined to the institution itself, but affect the entire scaffold of human thought, and therefore, human culture. <br></br><br></br>

That philosophy has lost its connection with the majority is not only attributable to the trends towards obfuscation and obscurantism, but  broader cultural trends that influence how we relate to information more generally. With so much media vying for our attention, our attention has been spread thin, fragmented. As we can all attest by this point, what captures our attention is, for the most part, that which most appeals to the deeper structures of our brain - that which has the most immediate reward value - rather than our higher ideals or best interests. Short, highly graphic material (Instagram posts, cat videos, porn etc.) in this environment wins the day, our time. Philosophy, unfortunately, requires both immense attention (relative to most activities) and is (as a rule) far less pleasurable than the content that is concentrated across the various digital rabbit holes we often find ourselves lost within. Thus the odds are stacked against the consumption of philosophy from the outset. Combine these realities with the realities of a world drowning in the informational equivalent of junk food and the stuffy, pompous, pretentious, aesthetic of philosophy and it’s not hard to see why we’re not eating our greens as we should. <br></br><br></br>

In order to revive philosophy, to reestablish the contemplative connection with the human mind, philosophy must therefore elevate the quality of its presentation. Amidst a hyper-competitive landscape of content, philosophers and artists alike must work to wrap their ideas in such a fashion that commands attention. Pretentiousness, obscurantism, and language games are all impediments to the consumption of substantive philosophy, barriers to a more enlightened populous, manifestations of pathology to be purged at all cost. While Wittgenstein was, in my opinion, unduly cynical about the reach of philosophy, he was onto something when he wrote, “What can be said can be said with clarity.” Anyone in the business of saying things should keep this front of mind. <br></br><br></br>

      </p>
      </div>
    </main>
  );
}

export default DeadPhilosophy;
