import React from 'react';
import styles from './Freedom.module.css'
import Footer from '../components/Footer/Footer';

function Freedom() {
  return (
    <>
    <main className={styles.container}>
        <div className={styles.box}>
        <h3 className={styles.preface}>Health as Freedom</h3>
      <div className={styles.content}>
        <p>
      Freedom is an obviously and notoriously tricky concept to pin down, philosophically. However, in everyday life, it’s a term we throw around all the time, and on some level, we all seem to know what we mean by it. So while it’s not immediately clear what freedom is precisely — in any kind of metaphysical sense, that is — our ordinary, colloquial use of the term, I suggest, reflects a reality of some sort that underlies it. In the case of freedom, there’s a there there, so to speak. That is our starting premise. Freedom is not a mere illusion, but a very real and important thing. Moreover, it’s a thing that we are justified in caring about, a thing that we ought to care about a lot more than we presently do. That’s the next premise. Together, we get something to the effect of “Freedom is real and something we ought to value, a lot.” To make sense of this claim, it’s necessary that we first do a bit of definitional work, so that when we’re talking about freedom, we’re talking about the same thing. Then we can begin to examine why it’s something we ought to value.
      </p> <br></br><br></br>

<h3 className={styles.header}>What Freedom Isn’t</h3>

<p>
At the outset, let’s make clear what freedom isn’t. Freedom isn’t freedom of the will. As I see it, however which way you cut it, the idea of ‘free will’ makes no sense. We have no control over the preconditions that led to our existence, no say in where we are born, nor what we are born with. We don’t have a say, in other words, in either nature or nurture, the twin variables that shape who and what we are, so how could we possibly claim to be free in the intuitive sense that most of us feel ourselves to be? Our will, contrary to the opinion of many, is in no way ‘free’ — at least not in any usual sense. Certainly, one can make allusions to the bucket of mysteries at the foundations of quantum theory, bend over backwards in order to leverage one mystery to explain another. However, there is no intellectually defensible grounds for pulling such a magic trick. In fact, it’s intellectually dishonest. At this point, there is nothing one can point to in order to justify the belief in the concept of free will. To the best of our knowledge, we’re all at the mercy of cosmic forces way beyond ourselves. It is certainly possible, however, that at some point our understanding could change; that an insight into the mechanics of existence somehow supports free will, and that our present inability to make sense of the concept merely reflects the all-too-real limitations of our intelligence and not the absence of its place in Reality. So, for now, whatever freedom is, it isn’t free will.
</p>
<br></br><br></br>

<h3 className={styles.header}>What Freedom Is</h3>

<p>
With that out of the way, we can now begin to think about what freedom is. At a high level of abstraction, like health, freedom is an emergent property of the universal Substance. Every blob — that is, every unit, fragment, mass — of Substance exhibits a certain range of freedom. Depending on how a particular blob of Substance is configured, such a blob could be said to exhibit more or fewer degrees of freedom than another blob. A rock, for instance, has very little freedom. A frog has more freedom than a rock; it can move on its own accord, for instance. In this most straight-forward sense, a frog can do more than a rock. The way in which it is configured permits a range of capability that the rock does not exhibit. Lest we be accused of discriminating against rocks, let’s draw another comparison, this time between two forms of animate Substance. Consider two frogs. One with all four of its legs, the other without any of them. The four-limbed frog is capable of hopping great distances, doing and moving as other four-limbed frogs do. In contrast, the no-limbed frog can’t hop at all, it can only wiggle around a bit. Accordingly, as a function of its physical impairment, the no-limbed frog cannot hunt for itself and is therefore dependent upon the assistance of other frog family and friends for its survival. All other things being equal, the first frog is more capable than the second. It is this most banal, down-to-earth sense, I suggest, in which freedom is a meaningful concept. However, banal though it is, when we stretch it to consider our own lives, it becomes rather interesting.<br></br><br></br>

At the heart of this conception of freedom is the notion of abilities or capabilities. We are free, I suggest, to the degree that we are able or capable, unfree in every respect that we’re not. This is obviously a rather sweeping statement, but I believe it gets at the crux of the matter. Let us illustrate by way of example. Consider two individuals. One who can do five pushups, the other fifteen. Who is the ‘freer’ of the two? Assuming this is the only respect in which the two differ, the answer would be the latter, of course. No matter how hard the former tries, no matter how much self-belief they have, no matter how much they believe in the idea of ‘mind-over-matter’, no matter how many motivational Youtube clips they’ve consumed, they can do no more than five pushups. They are physically incapable of doing more, in other words. Constrained by the relationship between the laws of physics and the configuration of their organism, they’re not free to do more than five pushups. Conversely, the latter individual is free to do more than five pushups — precisely ten more. I encourage the reader not to let the obvious triviality of this example conceal what is significant about it. The point is not that it is significant how many pushups one can do — though if we should value freedom, perhaps it’s more significant than is generally appreciated — but rather, that there are very real and testable ways in which we are free, and equally real and testable ways in which we’re not.<br></br><br></br>

The above was an example of physical freedom. But what about psychological freedom? Is there such a thing? If so, what does it mean to be psychologically free in a world without free will? First things first: psychological freedom, like its physical counterpart, is a meaningful concept. Just because we’re not the ultimate arbiters of our own fait does not mean that there is no sense whatsoever in which we may be free, psychologically. In a far more restricted sense, we’re all free — to a degree. That is, the degree to which we are capable. And while it’s not nearly as sexy as the notion of complete and unperturbed free will, it has the advantage of being real.<br></br><br></br>

The concept of psychological freedom is slightly blurrier than physical ability, for the obvious reason that the powers of the mind are mysterious in a way that our physical abilities are not. Put another way, our psychological capabilities are instantly malleable in a way that our physical capabilities are not. At the snap of a finger, our minds may become capable of something that, only a second ago, they weren’t. [Of course, the physical and the mental are inexorably connected — physical capabilities being contingent upon psychological capabilities, and vice versa — however for our sake, it’s necessary that we separate them.] That said, there are nevertheless rather clear-cut boundaries to our psychological capabilities which serve to illuminate the notion of psychological freedom. For instance, whether or not one is capable of composing a great work of poetry is hard to say (what with the inherent subjectivity of poetry, the ambiguity regarding what constitutes ‘greatness’ and the rest of it). But theoretically, any even remotely literate person is in principle capable of producing what may be regarded as a ‘great work of poetry’ however slim the odds may be. However, if one is illiterate — that is, incapable of working with the symbols that make for poetry — it is a certainty that such a person will not produce poetry of any kind, let alone the great variety. That is, not unless they first become literate. Here one may object “but anything is possible if one simply believes!” While I’m sympathetic to the sentiment, and respect its rhetorical value, I must (politely) disagree. No matter how intensely I believe I can speak French, I cannot speak French and will not speak French, that is, not until I’ve invested the necessary time required to learn the language. Until I learn the language, I’m not free — that is, capable — to speak it.<br></br><br></br>

Before we take a look at why we should value capabilities (freedom) and why we should include them in our conception of health, there is another facet to psychological freedom — one that is connected yet somewhat separate to the concept of capabilities — that seems to warrant address. While we appear to be at the mercy of cosmic forces we scarcely understand, inescapably bound to the unbreakable chain of cause and effect, there is a sense — however narrow — in which we appear capable of rising above it all, of transcending the reactivity that generally characterises our condition and exercising what amounts to the closest thing we have to an independent Will of our own. What I’m alluding to is an idea that is central to many of the spiritual traditions, one of the main ideals of the contemplative life. That is, the idea of overcoming our conditioning, the ideal of realising a state of perfect equanimity, or non-reactivity; to no longer be made angry or upset or bitter or jealous by things that would ordinarily have that effect. In short, to act with pure intention always, rather than react reflexively and predictably. This idea is somewhere near the bullseye of Enlightenment, and I suggest, much more than a mirage, and instead, a very real possibility for anyone willing to walk the Path. That it’s a destination that few of us are driving at represents the degree to which, as a culture, we are ignorant of the various landscapes of mind that are available to us all. Even within the traditions that recognise and explicitly aim at this end, the maps they’ve drawn are, at best, less than perfectly reliable guides. With time, with progress, I like to think, we will discover far more direct routes to this way of Being. For that’s exactly what it is: more than a capability — a superior piece of homeostatic software — though it is that too, rather a wholly different mode of Being, a fundamentally distinct ontology. The ontology of freedom.<br></br><br></br>

To be clear, I’m not making any metaphysical claims here, at least none that conflict with our common sense understanding of cause and effect, nor am I undermining the position on free will that I sketched earlier. Regardless of how equanimous or non-reactive one becomes, one is still participating in the same process of cause and effect as even the most reactive creature. By cultivating equanimity, one is merely changing the nature of their relationship with causality, rather than breaking with it entirely. Similarly, even the most realised, non-reactive individual cannot be said to exhibit free will, at least not in the philosophical sense. However, we might reasonably say that they display what is ostensibly a greater degree of free will; that is, the kind of free will we’re referring to when we employ it in a practical rather than philosophical context. In other words, the practical difference between voluntary and involuntary behaviour (see Locke on this point).<br></br><br></br>

<h3 className={styles.header}>Why Freedom?</h3>

Admittedly, justifying freedom — as a value — is a little like pulling a rabbit out of a hat. Though freedom is connected to facts about our organism and facts about the world, it remains one thing to call it a thing, and quite another to decry it a valuable thing. Much as we did with well-being, here too must we pull ourselves up by our bootstraps (as we must in order to get any intellectual affair on its feet and walking). Nietzsche famously had a big problem with this reality, warning that, lacking a genuine foundation, the entire moral, intellectual, cultural edifice we had constructed, was destined to crumble. This concern, while perfectly understandable — especially in light of the historical context in which he was working — was, like the rest of him, more than a little dramatic. While it’s true that values are constructed, the facts they’re grounded in are not; they’re discovered. Some values are justified, given the facts, while others are not. Where I’m sympathetic to Nietzsche is on the point that many of our values are arbitrary, harmful even. We have smuggled many erroneous ideas into our cultural framework throughout history, most often under the guise of divine wisdom. However, that doesn’t render the whole enterprise erroneous. Clearly Nietzsche didn’t think so, either. Otherwise he presumably wouldn’t have so polemically championed his own set of values as he did. Or perhaps he intended his work to be ironic. In any case, values are inescapable. They’re essential to the human project. And while we should do what we can to purge those that make no sense, provided the various facts of the matter, we must remain committed to the project, which requires our taking the issue of values seriously, rather than dismissing it as fraudulent from the outset. Yes, we are amidst a rather significant stage of cultural reconstruction, as Nietzsche saw as inevitable, but so we will always be. This thing will always be a work-in-progress. Whether it’s a work-of-progress, however, is on us.<br></br><br></br>

<em>
“We [contemplatives]… are those who really continually fashion something that had not been there before: the whole eternally growing world of valuations, colours, accents, perspectives, scales, affirmations, and negations. …. Whatever has value in our world does not have value in itself, according to its nature — nature is always value-less — but has been given value at some time, as a present — and it was we who gave and bestowed it. Only we have created the world that concerns man!”
</em> <br></br><br></br>
-- Nietzsche
<br></br><br></br>



Now back to freedom. Why should we care about it? That is, why should we value it? First and foremost, because of its relationship to well-being. While freedom by no means guarantees well-being, the two are tightly correlated. Our capabilities, as the source of our personal freedom, are also the source of much personal satisfaction, fulfilment, joy, meaning. And though they may not always elevate our well-being, they always have the potential to. They’re the tools in the toolbox, so to speak. Their being in the toolbox doesn’t guarantee that we will always or necessarily wield them to good effect, but at least it’s an option. In the case of capabilities, it’s truly better to be with than without.<br></br><br></br>

If we consider the lives of the most actualised individuals, we can see them as a process of cultivating and effectively leveraging capabilities; a process of expanding and relishing in their circle of personal freedom. To be sure, there are many ways to flourish in this world, many of which do not demand our constantly extending our capabilities. Some methods simply require our doubling down on a small collection of them. That said, there are no means by which one may flourish without any capabilities, however modest. Our flourishing is always and necessarily predicated on some capability. Capabilities — that is, freedom — is thus an essential precondition to human flourishing. In order to live a good life, by any standard, we must create and exercise our freedom.
<br></br><br></br>

There is another reason why we ought to value freedom. Just as we ought to value the quality of conscious experience, preferring well-being to suffering, so too should we value the possible range of conscious experience. By this I don’t mean the qualitative range of experience, the distance between the peaks and valleys of the moral landscape, but rather the quantitative range of possible experience, the total scope of realisable phenomenology. All other things being equal, it’s better for there to be more, rather than less, things to experience; more, rather than less, ways to flourish. And it is our capabilities, both those intrinsic to our organism and those that are extrinsic, those that are augmentative, that provide for our range of possible experience; with additional capabilities comes additional possible — realisable — experiences; that is, additional freedom, additional space of Being. In valuing freedom we are valuing the state-space of our existence. We are saying that we want the world of experience, the world we inhabit, the world of Being, to encompass as much as possible. In valuing well-being, on the other hand, we are saying that we want this space of Being to feel as good as possible. When combined, we’re saying: we want to feel as good as we can in any many ways as we can. That’s the money, philosophically speaking.<br></br><br></br>


When viewed through this lens, we get an interesting perspective on history. The whole process of civilisational development, through this lens, can be seen as one long (or short, depending on perspective) process of state-space expansion, a ballooning of capabilities and therefore possible experiences. With very little exception, we are free to do and be and experience more than at any other point in time. For the most part, and to an overwhelming extent, we are freer than ever. There is simply so much more to be had from life, from our humanity. And with all the challenges we’re presently facing, all the shit that has gone — and may go — wrong, it seems worthwhile taking a step back, if only for the briefest moment, to appreciate just what a tremendous achievement this — civilisation — is. Irrespective of how we’ve done on the well-being side of things (and I think we’ve done pretty good), there is no question that we enjoy unprecedented freedom. Yes, it may not be as evenly distributed as we’d like, but the fact remains. There is more to life than was before. This is huge, and should be recognised as such. And importantly, it should also be appreciated that this wasn’t inevitable. We take the development of civilisation, the development of technology, the advancement of freedom, almost as a given. But, presumably, things could have gone very differently. It’s not as if the tendency towards freedom is baked into the physics of things, right alongside the law of entropy or gravitation. At least not that we know of. Rather, or so it at least appears, we have fought for this freedom — literally and otherwise. We have given blood, sweat and tears for it, heart and soul and everything in between. And so we must continue.
</p><br></br><br></br>



      </div>
      </div>
    </main>
    <Footer nextTitle="The Current Consensus" nextPage="/consensus"/>
    </>
  );
}

export default Freedom;
