import React from 'react';
import styles from './Wellbeing.module.css'
import Footer from '../components/Footer/Footer';

function Wellbeing() {
  return (
    <>
    <main className={styles.container}>
        <div className={styles.box}>
        <h3 className={styles.preface}>Health as Well-Being</h3>
      <p className={styles.content}>
      What does well-being have to do with health? To be sure, this isn’t the first time this question has been posed. Indeed it’s a question that’s at the heart of the philosophy of medicine, an area of philosophy that we’ve been stumbling through — perhaps a little drunkenly — for the past number of paragraphs. And as with any even remotely interesting philosophical question, with this one, opinion is divided. There is no consensus. For the most part, there’s a clean split between the naturalists and the normativists on the subject of the relation between health and wellbeing. The naturalist will claim that in no way does health imply well-being, though they are likely to acknowledge that well-being is a fairly reliable indicator of health, a kind of happy accident of homeostasis. If we were to compare two individuals, both whom were in the optimal physiological range for their particular reference class, yet one had a higher level of well-being than the other (and let’s imagine it’s not only self-reported but actual well-being), in the mind of the naturalist, both are equally healthy. The fact that one experiences greater well-being than the other is, to the naturalist, entirely irrelevant. It merely reflects the differences between the two individuals’ physiology.<br></br><br></br>

The normativist, on the other hand, will argue that well-being is a vitally important part of what it means to be healthy. All other things being equal, she who feels better is healthier than she who feels worse. Not only is this view consistent with how we presently do medicine, and in-line with our most fundamental value, it’s also supported by our biological understanding of things. Feeling good, that is without external chemical intervention, is highly conducive to healthy physiology. Conversely, feeling bad is highly deleterious, physiologically. The evolutionary logic to this particular biological phenomenon is clear enough. Physical or psychological suffering serves as a physiological alarm, alerting one that something is up, something that needs correcting. Hunger pains, for instance, signal that one must eat or else it’ll be bad news. Well-being of any kind, in contrast, signals that things are good, a sort of physiological endorsement of one’s behaviour. ‘Keep on doing whatever it is that you’re doing,’ it says.<br></br><br></br>

Even when the suffering experienced is purely psychological, there’s very real, highly adverse physical effects. Consider depression. Depression is not only a reflection of poor health — either physical or psychological or both — it’s also a cause of it. Similarly, well-being is both a reflection and cause of good health. While it’s possible in principle to imagine two individuals with different levels of well-being and yet who — leaving values aside — are equally healthy, in practice, that’s not what we see, for that’s not how human biology works. It’s mistaken to think of two individuals who experience different levels of well-being but that ‘all other things being equal’ are equally healthy. In practice, all things are not equal by virtue of their divergent psychological compositions, compositions which are both grounded in and inform physiological function.<br></br><br></br>

In other words, psychological phenomena — consciousness and its contents — cannot be separated from physiological phenomena, for the two are one and the same. Well-being, indeed all conscious experience, is physiology. At the end of the day, it’s all just chemistry; various configurations of matter, with various properties at various levels of emergence. It’s not sensible, then, to speak of one’s physiology as distinct from how one feels, for how one feels is itself an emergent property of one’s physiology. That this point is not made clear in the literature is evidence of how deep the most extreme brand of mind-body dualism — ‘substance dualism’ — runs through our thinking. Even within the most scientifically literate circles (those intersecting with the field of medicine, for instance) the idea that we are a physical thing — a body with cells and tissues and organs — and a mental thing — a self, a spirit, a soul — and that the two can be divorced from one another, is remarkably pervasive. To be clear, there’s no question that we’re a physical thing as well as a mental thing. However, these two properties are part of the same unitary substance; that is, the fabric of Reality. That this isn’t fully appreciated, I suggest, can be attributed to the degree to which our experience of ourselves — that is, what it is like to be us — is so persuasively non-physical, that the idea that ‘all that we are’ emerges from a single substance is so counter-intuitive as to render the very notion absurd. Experience tells us — with literally every bit of personality — that we are this ethereal force, a voice that lives between our own ears, a spirit that couldn’t possible reside in any kind of physical substance. The weight of this experience is such that, even when we’re confronted with the facts of the matter, we’re unlikely to discard this intuitive, felt model of ourselves.<br></br><br></br>

If it’s indeed true that the entirety of our being is comprised of a single substance, as I believe we will confirm with time, there could be no metaphysical divide between one’s physiology and one’s psychology — that is, between the physical and the mental. Any sensible conception of health must therefore include both dimensions of our being, for they’re both ultimately properties of the same substance. Health is — at the highest level of abstraction — what emerges when the fabric, material, substance — call it what you will — of Reality is configured in such a way. Accordingly, our conception of health must incorporate everything there is to know about the various ways in which this substance can be arranged, the physiology, as well as what it is like to be arranged in such a way, the emergent psychology. One is not superior — metaphysically or otherwise — to the other, both facets are equally significant pieces of our humanity, both of which we must acknowledge if we are to understand, and ultimately better, our health.<br></br><br></br>

Following all this, and to hammer the point home, not only is it sound philosophy to incorporate well-being into our conception of health, given that — in practice — it makes no sense whatsoever to seperate health from value and that we are right to prefer one particular physiological configuration to another, it’s also sound biology, for well-being and suffering — and the entire phenomenological landscape that separates the two — are both emergent properties of particular physiology, non-physical properties that are just as pertinent to a rational understanding of health as their physical counterparts.<br></br><br></br>

So it makes sense to include well-being, as a value, into our conception of health. The next question is, are there any other values, analogous to well-being, that we should let in also? In short, yes, yes there is. To be healthy — I hope to make the case — is to be free. The extent to which we are healthy, in a very practical sense, reflects the extent to which we are free. Before we unpack this particular claim, let’s first explore the concept of freedom, and why it is something we should value.
<br></br><br></br>

      </p>
      </div>
    </main>
    <Footer nextTitle="Health as Freedom" nextPage="/freedom"/>
    </>
  );
}

export default Wellbeing;
