import React from 'react';
import styles from './WhatIsLife.module.css'

function WhatIsLife() {
  return (
    <main className={styles.container}>
        <div className={styles.box}>
        <h3 className={styles.preface}>What Is Life?</h3>
      <p className={styles.content}>
      There have been many attempts at defining life. Some elect to define it in terms of metabolism, while others frame it in terms of reproduction/replication, self-organisation, information processing or even consciousness. Whether any have been successful, though, is for posterity - the great arbiter of history - to judge. And whether it matters is another thing all together. Fortunately, for the purposes of my argument, we need not create an elaborate or even universal definition of life. All we need to accept is that there is such a thing as life, and that it is distinct from another set of things, that is non-life. As soon as we admit of this distinction, however, there is a pragmatic need to conceptually distinguish the two. If we accept that there is such things as life, and if we claim that these things are Good, this begs the question, What is it? So we cannot sidestep the question entirely. But rather than attempting to delineate some kind of novel/technical definition of the phenomenon, I suggest that our common sense understanding will suffice. <br></br><br></br>

Life, as we know it, exhibits a number of properties. It has metabolism, it grows, it reproduces (it has DNA), it processes information (in the technical sense and beyond*), and yes, it seems to exhibit consciousness - or so we can only assume. For those who wrestle with defining life, the challenge lies in the exceptions to the rules. While most things we would generally refer to as “life” fit the bill entirely - as in, they display all the aforementioned qualities - others do not. Some things certainly appear “life-like” but whether or not they are indeed bona fide life would depend on whether or not you take each of these criterion to be pre-requisite. Take viruses, for instance. Viruses exhibit much of the same biochemistry as “living” organisms - with DNA, RNA etc. - yet they cannot reproduce on their own. Instead of harnessing their own cellular machinery in order to replicate, they leverage that of others, they parasitise. So are they alive? Or are they not? Throughout history, we’ve gone back and forth on this question. Today, viruses are generally regarded as occupying some kind of grey area in-between life and non-life - ‘life-ish’. This presents a problem for anyone attempting to create a binary definition of life. For those who conceive of life as a continuum, however, there’s no problem. Viruses are simply life-ish, bacteria more so, plants even more so again, culminating in perhaps the most life-y of all life, humans. Problem solved.<br></br><br></br>


At a higher level of abstraction, beyond metabolism and beyond even information processing, life appears to be but an emergent property of matter. As our everyday experience of the world confirms, there are two types of matter-stuff that we ordinarily encounter: animate and inanimate stuffs. For most of human history, we’ve viewed the former as being wholly distinct from the latter. Where animate matter was animated by a certain élan vital, or vital force, a special non-physical substance, inanimate matter was devoid of such ethereal special-sauce, just regular-degular matter. Today, we - ‘we’ being the scientific establishment - no longer subscribe to this view (known as vitalism). Instead, we now take the view that life is also mere regular-degular matter, only regular-degular matter configured in a specific way that makes it “come alive”. What distinguishes life from non-life - or animate from inanimate matter - is not what it’s made of, but rather how it’s put together. In other words, there’s no special sauce, here there or anywhere, it’s plain ol’ sauce, all the way down. <br></br><br></br>


In truth, life is largely a mystery. We know it’s made of the same stuff as the rest of stuff, but whether or not it contains something extra is, at this point, impossible to say. Some have even speculated that living systems adhere to and embody physical laws hitherto undiscovered, and that until we ascertain what these laws are, life will forever remain outside the field of human understanding. That this idea is even entertained - and by legitimate folk no less - speaks to the stupendous complexity of living systems. Postulating additional laws of physics is the scientific equivalent of mysticism, after all. In any case, it’s an awesome idea. But of course, many are convinced that life follows the same old two-dollar laws of physics as the next mundane physical object, that from relatively simple physical principles great complexity emerges. American computer scientist Stephen Wolfram, for one, even thinks he’s figured the whole thing out. Either way, life’s a crazy fact of our existence. And that’s the essential point: it is a fact of our existence. Wherever you draw the dividing line, there is life and there is non-life, living and non-living systems. Regardless of whether you buy the Good piece, life definitely is. <br></br><br></br>


So life is. But why’s it matter? What makes it Good? As remarkable as the molecular and cellular processes that underpin metabolism, respiration, replication and indeed the rest of life’s mechanics are, they are not in themselves valuable. Though inspiring, it’s not the chemical complexity of life that makes it Good, but rather the subjectivity that emerges from it. Consciousness, in other words, is what makes life Good. While consciousness is no less mysterious than life, as far as we can see, consciousness appears to be an inherent - or emergent - property of life. In fact, consciousness has even been referred to, by at least one neuroscientist, as the “feeling of life itself”. Now whether or not consciousness is always present in life or whether it appears only in more “evolved” forms, is impossible to say at this point. That life is prerequisite to consciousness (of the sort that we ought to care about*), however, seems as good as certain. Now this is not to suggest that consciousness is substrate dependent, that is that its existence is contingent upon carbon-based meat suits such as our own, and that conscious AI is therefore impossible in principle. Rather, it’s simply to suggest that, were we to create conscious AI, we would have also created life. Life and consciousness, I suggest, go hand-in-hand. <br></br><br></br>


Consciousness, as the source of experience (indeed as experience itself), is the basis of value in the world. It’s what saves the universe from being an expanding void of meaninglessness, a cosmic show of fireworks with no audience. Without consciousness, there would be matter but nothing that matters. It is therefore for the same reason that we owe a moral duty to cultivating and positively engineering consciousness that we owe a duty to protecting and serving life. If consciousness is continent upon the existence of life, which we have every reason to believe is the case, then it is ultimately in the service of life that we must live. <br></br><br></br>

To be sure, life is not inherently valuable. It is possible to have life and for it to be of negative value. For while life is prerequisite to value, it is not positively valuable in itself. The positive value of life is not intrinsic to life, but rather in the quality of consciousness that life gives rise to. A life characterised by permanent suffering and misery, for instance, is a life we have no reason to care for. Indeed, life is only valuable when it is configured in such a way as to make well-being possible. Of course, this is not to say that a life is only valuable when there is well-being. For suffering in the present can and reliably does lead to well-being in the future. Instead, it is simply to say that, were it not for the possibility of well-being, whether now or in the future, life would give us nothing worth having; on the contrary, such life would be something we actively sought to prevent. Life is Good, in other words, not because it is in itself Good but because it confers the possibility of, indeed is prerequisite to, feeling good. <br></br><br></br>

      </p>
      </div>
    </main>
  );
}

export default WhatIsLife;
