import React from 'react';
import styles from './DeathIsBad.module.css'
import Footer from '../components/Footer/Footer';

function DeathIsBad() {
  return (
    <>
    <main className={styles.container}>
        <div className={styles.box}>
        <h3 className={styles.preface}>Death Is Bad</h3>
      <div className={styles.content}>
        <p>
        If life is Good, then it stands to reason that we should all prefer more rather than less of it. That’s not what we find, however. If you were to survey a random selection of humans in the 21st century, asking them whether - if provided the chance - they would like to live forever (or even significantly longer than the present average, for that matter), surprisingly few will answer in the affirmative. It’s one of the more interesting philosophical experiments one can run. Should you happen to run such a survey for yourself, depending on your sample population, you’ll receive a range of answers spanning in sophistication from “Nah, fuck that” to “No way, life would be devoid of meaning,” and every conceivable position in-between. When pushed to articulate the logic that underpins their almost instinctual aversion to the notion of a long - let alone eternal - life, some number/version of the following answers will generally result: <br></br><br></br>

1. Life would be boring<br></br>
2. Life would be meaningless<br></br>
3. Would be painful to watch everyone around you die<br></br>
4. You can’t have life without death (without question the most interesting) - yin/yang. <br></br>
5. The population would explode and the world would end<br></br>
6. Death is natural<br></br><br></br>

Let’s take a look at these, one at a time.
     <br></br><br></br>
     </p>
     <br></br>
<h3 className={styles.header}>#1 Life would be boring</h3>

<p>
This one’s perfectly intuitive and goes something like the following. Life is, from time to time, boring. With infinite time, it might seem to follow, life would be infinitely boring. Without finitude, we would never do anything. Without an expiry date, there would be no haste, no hustle. We would all surely become paralysed by possibility, drown in the vastness of eternity. To be sure, eternity is a long time. But we need not posit an eternal life in order to elicit this same reaction. The thought of a 200-300 year old life is enough to scare most people. The question is, Why? Why should we feel as though extending our window of experience should do anything but enable us to do/be more? The reason, I suggest, is that we are simply constrained by the limits of our imagination, parochialised by the vagaries of history. We imagine that an extraordinarily long life must be an extraordinarily boring one precisely because we fail to imagine the possibilities of such a life. Rather than conceiving of the myriad ways in which a much longer lifespan would affect the architecture of our lives, and envisaging the opportunities, we simply map the trajectory of our present lives onto a much longer timeline. We imagine completing all that there is to complete by the age of 80 and then sitting around twiddling our thumbs for the rest of our days. But why should this be the case?  One specific failure of imagination here is that most people assume that an extended lifespan would simply mean more years of being old. But let’s assume that if we have the capacity to extend lifespan, we also have the capacity to extend our healthspan. How would you feel about living substantially longer if that meant you were able to live substantially longer in the physical shape of a 25-30 year old? This reformulation is enough to alter the tune of many anti-longevity folk. But not all. Life would still get boring, they will claim, whether you were stuck in the body of a 20-something or an 80-something. Without the spectre of death looming, life would invariably wilter. This brings us to the second most common objection.
</p>
<br></br><br></br>

<h3 className={styles.header}>#2 Life would be meaningless</h3>

<p>
That it is death that breathes meaning into life is also an intuitive concept. The more scarce, the more finite; the more sacred, the more precious. The more sacred, the more precious; the more meaningful. So it is with commodities, so it must be with life. On its face it’s a perfectly logical position. But unlike commodities, however, life is inherently valuable[ *So long].* Its abundance or lack thereof has no bearing on its moral value. The value of your life, for instance, is in no way shape or form rendered less - less sacred, less precious, less meaningful - as a result of their being others around you who also have it. When it’s configured in such a way so as to give rise to positive experience, life is valuable. When not, not. Life is not a commodity, it’s the very substrate of meaning. <br></br><br></br>

Now of course, this is not to deny that death - in the context of our present all-too finite lives - serves a function, provides value. That our life could end at any moment - and that best case we have only a hundred or so orbits around the sun - certainly motivates us to do and be while we can. It’s the ultimate forcing function. That said, there is no reason in principle that our lives should be governed by the fact of their inevitable doom. While it lights a certain fire, there are many ways to move through the world, many ways to motivate action, many ways to find meaning. Though our finitude is reason to cherish what moments we have, it’s not the only reason, nor is it the best. We should cherish our moments irrespective of how many we have, simply because inherent in every moment there is something capable of being cherished. We cherish because we can, not because one day we cannot. For it is in moments that there is meaning, meaninglessness only in their absence. There is Being and there is Nothingness. ‘To Be or not to Be’ might be the question, but ‘to Be’ is most definitely the answer.<br></br><br></br>

</p>
<br></br>
<h3 className={styles.header}>#3 Life would be painful</h3>
<p>

The concern here is that, were we to live much longer lives than we currently do, we would bear witness to proportionately more death and therefore be subjected to the harrowing misery that ordinarily accompanies it. Life, in such a case, would be rendered intolerably more tragic, the reasoning goes. We would live only to watch those we love die. Our supranormal longevity would thus be a curse of the cruelest order. Of course, were this the deal, things would be tough. Though it is by no means clear that we wouldn’t adjust to such circumstances. Indeed perhaps we would develop an entirely new psychological program for dealing with death, learn to live fully amidst its haunting presence. Our families would become a distant memory and friends would arise and pass like the seasons, yet their lives would remain - somewhere - within us forever. And perhaps that would be enough. Perhaps we would learn to live accordingly. But perhaps not. In any case, it doesn’t much matter. For this objection is predicated on the assumption that we (being the recipients of the philosopher’s stone) would be granted eternal life (or just a really long one) while others around us would live their normal human lifespans. Imagine, instead, that we all got the same deal, that we’re all provided access to the fountain of youth. Life might still be filled with tragedy, but it would be no more tragic than it already is. The movie of our lives would still contain all the dimensions of the human experience, it would simply run a bit (or a lot) longer. So long as we are architecting our lives intelligently, this should only be a good thing. A good movie is a Good movie, however long it runs. 

</p><br></br><br></br>

<h3 className={styles.header}>#4 Life and death are one and the same</h3>


<p>
This is the metaphysical objection and certainly the most sophisticated of the lot. The idea, in a nutshell, is that death is an inextricable dimension of life, life’s other half, as it were. For every ounce of life, there is a corresponding ounce of death. It’s the cosmic order, y’know, yin and yang. To upset the balance (provided we even have the capacity) would be to upset the balance of Reality, an absolute aberration. Although any rationalist/skeptic is unlikely to be moved by the purely metaphysical dimension of this claim, there is a very down-to-earth - indeed scientific - fact that lends it credence. That is, that death is a process that is constantly taking place within life. As human organisms, we are collections of trillions of different cells. At any given moment, many of these cells are dying off while new cells are emerging. Contrary to our felt experience of what we are, we are not a single, fixed, discrete entity but rather an emergent property of an entire inner biological universe that is in constant, incessant flux. Death, it’s true, is an irrefutable fact of life. Be this as it may, it does not follow that life is synonymous with death. Death is a process that is inexorable from life, indeed a biologically necessary process, but the two are not one and the same. Inside any organism, at any given time, there is death taking place. But it is the predominance of life that is its characteristic feature. When life is no longer the predominant characteristic of any organism, that organism could be said to have ‘died’. This raises the question, Just what is an ‘organism’? <br></br><br></br>

‘Organism’ is the term used to denote an individual form (or unit*[ Cell is also a unit of life, but in a different sense. ]) of life. A kangaroo is an organism, so too a platypus, so too an eucalyptus tree, and of course, soo too is a human. Interestingly, however, besides single-celled organisms, organisms - such as the above - are in fact made of many other organisms. The human microbiota, for instance, is comprised of trillions of bacterial cells. Inside each and everyone of us is an entire civilisation of bacteria. We are Russian dolls, for real, we contain multitudes. In what sense does it make sense, then, to champion the extension of life - and human life, specifically - when what we are made of is life, life that extends beyond the life of our individual human organism? Now this is a question that cuts rather deep, to the very core of life’s mystery in fact. It leads us to ask whether life is a process best understood at the level of the individual organism - be it plant, animal or bacterial - or instead a fundamentally planetary (or even universal) process. And if we decide that life is an organism-level process, or at the least the most relevant level (relevant to what?), how are we to reconcile the multitudinous nature of organisms? Personally, I think life can only be explained as a kind of cosmic scale process, for there is strictly speaking only a single process: the process of Reality unfolding, whatever that is. We are all subservient to - and contingent upon - the great cosmic Something. Life’s secret is hidden, somewhere, in the laws of physics - inevitable. <br></br><br></br>

If life is a cosmic process, on what grounds could we justify valuing the life of a human over, say, the life of a bacterium? Why should we care about extending our own lives, rather than merely advancing the echidna’s evolutionary agenda, for instance? Whether the fundamental unit of life is the individual cell, the planet or the entire universe, it remains that the only morally significant feature of life is the quality of consciousness that it gives rise to. As such, we are right to value those forms of life that appear to embody deeper/richer/better states of mind. All life may have evolved equally, but not all life is equally valuable. <br></br><br></br>

Of course, there is an epistemological dilemma here, in that we cannot know for sure - and may never know - the mind of another. It’s certainly hard to imagine ever having access to the qualia of another species; what it is like to be a bat, for instance. But at least intuitively, there certainly appears to be a qualitative range of conscious experience. A Venus fly trap certainly appears more conscious than a bacteria, an octopus more conscious than a worm, and a human more conscious than, well, perhaps any other animal. There is a blatant hubris - not to mention anthropocentric bias - of course in placing ourselves atop the pyramid of conscious experience, but there is at least some evidence to suggest that our inner lives are indeed more rich and varied than any other creature, at least on earth. If nothing else, our culture is a testament to the uniqueness of the human experience. 

<br></br><br></br>

In other words, we value human life over other forms of “lower” life - bacteria, for example - based on the assumption that our conscious experience is qualitatively superior. While there is no way to affirm of falsify this assumption, it is nevertheless justifiable in light of the circumstantial evidence, so to speak. While this logic is obviously self-serving, should it come to light that we are in fact ‘lesser minds’ than we thought, to the degree that our presence conflicts with higher forms of life in the biosphere, the same moral logic would then run counter to our interests. Moreover, even if our minds are the most significant moral objects in the universe, were we to create minds - artificial or otherwise - that were superior to our own, we would then be beholden to their interests, morally speaking. If it was in the best interests of the AI to turn us all into paper clips, we would have no grounds - again, morally speaking - on which to object. In order to preserve our moral dignity, we would have no choice but to comply. 
<br></br><br></br>

But back to the issue of death. If we are made of life, and if the life we are made of (at least partly) outlives us, in what sense do we really - ever - die? This one’s rather simple. Although the microbes we are comprised of may outlive us, it is us - the emergent structure that results from the configuration of our constituent parts - that we care about, that ultimately dies. There’s really no great paradox here. The things that make us possible live on, but the thing we value - our physical organism - ceases to be. In the same way that we are not baffled by the fact that a building could be destroyed by an earthquake - even though all its parts are still in existence - we should not be baffled by our own death. When we are put together in just the right way, We Are, when that configuration falls apart - or otherwise changes beyond a certain point - We Are Not. In this sense, death really is the opposite of life, it is the cessation of life which takes place at a particular scale, a particular level of emergence. Death is the Nothingness that haunts life’s Being. They are closely related, but they are not one and the same. <br></br><br></br>

</p>
<br></br>
<h3 className={styles.header}>#5 The population would explode</h3>
<p>
A substantially greater population would be a natural corollary of our living longer. While it is true that as nations develop fertility rates generally decline, were we to substantially increase the average human lifespan - by orders of magnitude, for instance - it is almost assured that there would be far more of us around. Far more of us, of course, means far more to feed, far more to clothe, far more to shelter. Given our current rather precarious relationship with the biosphere (and each other), it’s perfectly natural to infer that a much larger population would be environmentally and socially untenable. If you assume no - or very little - progress across the relevant vectors, I believe this inference would be correct. If our technology - in the broadest sense - for living with each other and the planet remains as it is, it’s hard to see the planet supporting our existence deep into the future. We’re already having a tough go with 7.8 billion of us. With that number headed towards 10 billion by the end of the century, there’s ample cause for concern. Fortunately, I believe in the reality of progress; not progress of the pre-determined inevitable variety, but progress of the “if we put in the work it might just happen” sort. <br></br><br></br>

In order to sustainably support the existence of a much larger population than current estimates (say 15-20 billion +), it would indeed require our fundamentally rethinking the architecture of society. All the way up, from food production to transportation. We would need to find new ways of living within the resource constraints of the planet, while simultaneously inventing ways of expanding those constraints (mining the galaxy rather than our own backyard, for instance). Most critically, however, it would require our moving beyond the earth. Resource constraints are a fundamental fact of our existence on earth, and so it will always be. And so if we take the view that more rather than less of us is preferred, as I argue we should, then at some point - should we be successful in managing the next few hundred years - we will be forced to find/create new homes among the stars. Not only will this (hopefully) become a necessity, what an inspiring version of the future! Even though we are nowhere near the theoretical carrying capacity of the planet, at some point we will be. If so, it would mean we’re winning. In preparation of this, we should be setting our sights beyond. Although it might seem absurd, remember, so is our very existence in the first place. And though it might seem premature planning for such a time, remember, Rome wasn’t built in a day. Rendering humanity a genuinely space-bearing (type III) civilisation will take time, and it won’t happen by accident. It will require our thinking in time scales that we are unused to. And that’s a good thing. We could do with extending our gaze beyond quarterly financial reports. <br></br><br></br>

In sum, although the population implications of greater longevity present challenges, they are challenges that we are - at least in principle - capable of overcoming. Moreover, they’re challenges that we must overcome, irrespective of whether or not we make substantive progress on the longevity front. Whether we are successful in radically extending human life or not, we have no choice but to rearchitect our way of living. And while the kinds of solutions necessary to supporting a population of 10 billion may differ in degree from those necessary to supporting a population 2 - 10X that, they do not differ in kind. If we can solve the former class of problem, soo too can we solve the latter. <br></br><br></br>

</p>
<br></br>
<h3 className={styles.header}>#6 Death is 'natural'</h3>
<p>
Another objection to treating death as a problem to be solved is that “death is natural”. Death, it’s true, is entirely natural. But so too is rape, genocide, cancer, tribalism and all of its odious manifestations. This kind of thinking reflects what’s known as “the naturalistic fallacy,” the mistaken idea that just because something is natural it must, by extension, be good. Of course, something’s ‘natural-ness’ has never been grounds for our dogmatically accepting it. On the contrary, progress has been made precisely because we don’t accept what’s natural, because we subscribe to the idea that what’s natural can and should be made better. Our refusal to accept what’s natural is, in many respects, the most powerful idea we’ve ever embodied. The same should go for death. It is natural, no doubt, but it ought not to be. 
<br></br><br></br>

In order to fully purge the naturalistic fallacy from our minds, it should also be noted that, by definition, everything is natural. Everything is ontologically equal, everything is made from the same stuff. How could there be something unnatural in a fundamentally natural world? Either the world is natural or it’s not. If it is, everything is natural. If it’s not, everything is synthetic. In either case, everything is equivalent - ontologically speaking. <br></br>
</p>
<br></br><br></br>
<h3 className={styles.header}>Ending death (at all rational cost)</h3>
<p>
    By now, it should be clear that death is Bad. Like, really Bad. And so it follows that it is our moral duty to prevent it, to overcome it, to stave it off. It does not follow, however, that we should stop and drop everything we’re doing in order to focus on the problem. Instead, all I argue is that we should work on the problem of death to the degree that is practically feasible/rational to do so i.e “at all rational cost”. Obviously, managing civilisation requires many things of us. There are certain things that we simply must do if we want things to stay afloat, keep the cogs turning - education, basic health care, food production, for instance. All I am suggesting is that, given the moral stakes, we should allocate far more resources towards the problem of death than we presently do. Now what constitutes “rational cost” is impossible to establish. There is, after all, some possibility that death is a fundamentally intractable problem. There may exist certain laws of physics (or emergent biological laws) that we are not yet cognisant of, that render greatly extending human life (beyond our ‘natural’ limit) impossible. Possible, yet unlikely. In such a case, almost any investment made in the area of longevity would - at least prima facie - seem irrational. The thing about investing in the problem of death/longevity, though, is that it simply means investing in fundamental science, both within and without the field of biology (physics, chemistry and biology are all arms of the one Science, after all). Therefore, even if the problem of longevity and death prove to be intractable (again, unlikely but in principle possible), we would still benefit enormously by increasing our investment in fundamental/basic science. By investing in the longevity project we will invariably make other discoveries that materially improve the plight of humanity, on both the environmental and public health sides of the equation. Now precisely what that investment should amount to as a percentage of global GDP is a largely academic question, albeit an especially important one. What is clear, however, is that given the historical relationship between basic science and human progress, plus the enormity of the potential upside, we should be investing considerably more than we are at present. <br></br><br></br>
</p>
<br></br>
<h3 className={styles.header}>What about the afterlife?</h3>
<p>
There is another metaphysical/theological objection to the idea that death is something to be avoided at all rational cost, rather than welcomed/accepted/embraced. Obviously, many religions believe in the notion of an afterlife, a hereafter. Most popularly, the Christian metaphysic posits the existence of a heaven and hell, within which one spends eternity depending on their conduct during their human life. Similarly(ish), Buddhism promotes/subscribes to the notion of Karma, the cycle of death and rebirth, a kind of cosmic flywheel that keeps spinning until one transcends the game entirely through the attainment of Enlightenment. Now just what if there is a hereafter? Moreover, what if it’s really really Good à la heaven? What if human life is just some mediocre in-between state, a sort of second-rate loading room, and that by avoiding death we’re unwittingly avoiding or simply delaying eternal Bliss? Here, contrary to the claims of theologians the world over, we’re really driving blind. Of course, we have no idea what happens after the here. There might be Nothing, or, there might be Something. Something really Good, even. Now of course the converse might also be true, there might be Something rather Bad. In any case, it’s a guessing game. Personally, I like the odds - I’ll take the bet that life is better than what (if anything) happens after. That said, it would make sense to adhere to some kind of precautionary principle on the off chance that what happens after is a lot of fun. No matter how good we get at modulating life - indeed even if we achieve some version of immortality - we should always reserve the ability/right to die. In a word: optionality. We ought to have as much life as we want, but we ought to be able to do with it what we want, even if that means doing without it. 
<br></br><br></br>
</p>
<br></br>
<h3 className={styles.header}>Talk is cheap</h3>
<p>
While a truly surprising number of us take issue with the longevity project, on abstract philosophical grounds, it’s revealing to observe how we actually deal with death in practice. For the most part, we are in fact fundamentally pro-life in our behaviour, at both the individual and societal levels. That is, we do what we must in order to stay alive. We eat, we drink water, we sleep. When we’re sick, we do what we can (what we can be bothered to, at least), in order to get well. Moreover, a growing portion of us are going to increasingly elaborate lengths in order to ensure we stay alive for as long as possible. Special life-promoting diets, fasting, exercise, saunas, ice baths, supplementation etc. You name it, if it extends life (or at least claims to), chances are it’s becoming more popular. At the societal level, one need only look at the health care statistics to get a sense of how much we value life - and therefore disvalue death. In the US alone, for instance, north of $3 trillion dollars annually is spent on health (read: life) care. [ From paper below “The Myth Regarding the High Cost of End of Life Care” 2.7 trillion in 2011. Assuming that number has increased. Find better data. ] Of that sum, at least 10-15% is spent on what’s known as “end-of-life” care; in a nutshell, squeezing the last bit of life out of a dying human, delaying (by days, weeks, months) the inevitable. <br></br><br></br>

Claims that death is a perfectly natural occurrence and therefore something to be accepted stoically when it comes, while admirable on some level, flies in the face of the actual ‘on-the-ground’ reality of our relationship with death. We pay lip service to the existential value of death, yet allocate a third of our collective resources towards preventing it (either directly or indirectly), even when it’s imminently inevitable. Talk is cheap, as it goes. While it might be seductive to chalk up our embodied response to death as nothing but fear, a kind of moral failing, I suggest that, on the contrary, it reflects an entirely rational - and indeed the only morally defensible - philosophy of life. Life is Good, we therefore ought to preserve it! The issue with our current approach is thus not that we aren’t valuing life, but that the means by which we are attempting to preserve/promote it is irrational. Our current model of health care is one based on ‘sick-care,’ a paradigm where we take disease once it is already manifest, then seek to treat it by any means - whether slash, poison or burn - necessary. For a variety of reasons, both biological and economical, this approach is fundamentally flawed. Although sick-care will/should always be a part of our medical framework, it should not be the primary orientation. Instead of attempting to treat disease once it has already materialised, we should be allocating our resources towards ensuring such disease doesn’t materialise in the first place. Prevention over treatment, as the cliche goes. And although very few would disagree with this approach, at least in principle, if taken seriously, it implies a radical rearchitecting of our ‘health-care’ system and indeed society writ large. If we are serious about preventing disease, as serious as we should be, it would mean investing far more aggressively in a variety of things, from understanding the fundamental processes that underpin life, to early stage detection and perhaps most pressingly, the nature of our environments - quality of our food, air and water supplies, for starters. As sensible as it sounds, it’s a strategy that’s highly divergent from our current fixation on the individual manifestations of disease states, as well as diametrically opposed to many of the vested interests that support/promote the present paradigm. <br></br><br></br>
</p>
<br></br>
<h3 className={styles.header}>Acceptance as coping mechanism</h3>
<p>
Although the aforementioned objections are slightly different in shape as well as texture, they’re all fundamentally attempts at reconciling the reality of death. They’re coping mechanisms. We accept death because we must, because we have no choice in the matter. To live in constant fear of death is to never live at all, and so we rationalise it, pretend it’s a good thing. We tell ourselves stories of an afterlife to help us swallow it, the most unpalatable pill of all. While it’s an evolutionary strategy that has surely served well, at some point we must recognise that our intellectual acceptance of death is a bug rather than a feature. Until such time that we have conquered death entirely, we should make peace with the fact of our eventual demise, take it as it comes. No-one should go out kicking and screaming. However, making peace with the fact of our inevitable individual demise is not the same as accepting death as an inviolable, immutable law of human existence. Death, one hopes, will eventually be held in the same vein as the horse-drawn carriage and clay tablets: quirks of human history, steps along the path of progress. 
<br></br><br></br>
</p>


      </div>
      </div>
    </main>
    <Footer nextTitle="The Historical Background" nextPage="/background"/>
    </>
  );
}

export default DeathIsBad;
