import React from 'react';
import styles from './Authenticity.module.css'
import Footer from '../components/Footer/Footer';

function Authenticity() {
  return (
    <>
    <main className={styles.container}>
        <div className={styles.box}>
        <h3 className={styles.preface}>Authenticity</h3>
      <p className={styles.content}>

      In the ‘enhancement literature’ there is this concept of ‘authenticity’. Authenticity means many things to many people, but in this particular context, it refers to the idea that there is something essential to our condition that makes us who and what we are, and that thing, whatever it is, is Good. If we were to intervene in ourselves, beyond a certain point, we would lose our authenticity, it’s argued, and that would be Bad (it’s also argued). Exercise and meditation and so on are perfectly fine, therefore, because they don’t corrupt our authenticity. They leave our super special human essence in tact. Neural implants, however, would (perhaps) make us something entirely different. It would render us wholly Other. <br></br><br></br>

The trouble with authenticity arguments is that authenticity itself is an incredibly hazy notion, almost impossible to pin down. What is essential to our humanity, and what does it mean to be ‘true’ to it? When you consider what the “self” really is, a sequence of experiences strung together across time with a certain degree of continuity, it’s hard to place authenticity anywhere meaningful.[ There are of course other definitions of human identity. This, being Parfit’s conception, however, is the most legit. See Reasons and Persons for more. ] If what we are is a set of experiences defined by certain parameters, so what if the parameters - and therefore the experiences - change? Surely our physical form is not absolutely essential. Presumably, we would still be authentically human if we had twelve limbs, even two heads. <br></br><br></br>

The next issue with authenticity, as a basis for arguing against enhancement, is the assumption that What We Are is Good. While I’m perhaps uniquely sympathetic to the idea, you could certainly forgive one for thinking otherwise. Simply looking at our past, it’s clear there’s at least considerable room for improvement. And, if it so happened that such improvement came at the cost of some amount of authenticity, that might be a fair price to pay - one could certainly, and quite convincingly, argue. 
<br></br><br></br>
Another problem with claims re the sanctity of authenticity is that they tend to rest on a very particular conception of what we are, one that takes our psycho-physical organism as primary, at almost the complete exclusion of the world around us. What does that mean? It means that proponents of authenticity tend to be biased against things that impact directly our physiology, our inner world, yet curiously impartial to things that change the world we live in, our environment. Of course, we are psycho-physical organisms. Whatever we do to our physiology is changing us, whether trivially or fundamentally. But we are also psycho-physical organisms embedded in the context of an external world. We are the world as much as our hands and feet, in other words. As such, we cannot be studied in isolation from the very context of our existence. Or we could, but it wouldn’t tell us much. For to understand someone, anyone, you must first take into account the world in which they live. 
<br></br><br></br>
If we take our physical environments seriously, consider them as literal extensions of who and what we are, it stands to reason that we should be equally concerned about changes we make to the world as we are to changes we make to ourselves. What does it mean for authenticity, for instance, that we are have, through our relationship with technology, become ostensible cyborgs? Are we something fundamentally different than we once were by virtue of the fact that the majority of us spend the majority of our days hunched over a desk in front of a computer screen? What does it mean, for that matter, to be human in a world where half our lives are lived online? What about the fact that we can move through time and space like magic? Does that mean anything? Are all these changes to what we are merely changes in degree, or do they represent fundamental changes ‘in kind’? Whatever the case, it’s clear that the conversation around human enhancement, for it to make any sense at all, has to include modulations to the world outside of our skin and bones, for our humanity is inexorable from our world/s. 
<br></br><br></br>
Critics of this kind of argument - we’ll call it the the ‘extended phenotype argument’ - might respond by asserting that the difference between changes in the world and changes to ourselves is that the former are less of a threat to our authenticity as they’re less connected to the ‘intrinsic qualities of our humanity’. Changes to our environment, though they might change us in superficial ways, they’re further removed from the core of our identity. Even though the world has changed almost beyond recognition, throughout history, it has not altered the essence of what we are. We are still, at root, the same kinds of things we always have been. Now this might be true. Perhaps, despite the transformation in the external world wrought by history, the essential character of our identity remains in tact. However, the idea that changes to our physical environment, such as those we have experienced, do not affect our humanness is patently absurd. The ways we communicate, the modes of work we engage in, the foods we eat, the air we breathe, the books we read (or don’t read) - the structure of our lives - absolutely impacts the essential features of our humanity; how much we care, how much we love, how much we know.
<br></br><br></br>
With respect to technological changes, specifically, a common intuition seems to be that they’re not as ethically significant as, say, germ-line changes to our genome, because we can always opt-out of the former. Technology we can always fix/get rid of, changes to our germ-line, however, are irrevocable. Understandable as this intuition is, it’s not entirely grounded in the reality of things. Although we are absolutely free, in principle, to opt out of the technology of our time, in practice, there is very little freedom to be found. The degree of cultural resistance that one would face in giving up certain kinds of technology, for instance social media, renders them - in effect - non-optional. Given the mechanics of culture, and our minds that constitute it, what appears as free choice is in fact nothing of the sort. At least with germ-line editing, we are aware of the permanency - or at least quasi-permanency*[ It should be noted that germ-line changes could be corrected, by the very same means they were made in the first place. If we have the power to fuck things up, at the germ-line level, it stands to reason that we also have the power to fix things.
    <br></br><br></br>
Add something about whether or not to make a particular enhancement at the germ-line level is really just a matter of convenience / pragmatic. If it makes sense to make the change at the level of the germ-line, so that we don’t have to make the changes on every individual, we should do so. If, for whatever reason, germ-line changes are untenable - as a matter of practice - then they are untenable. It’s not that big of a deal either way. ] - of the changes we are affecting. With changes to the external environment, however, we are ostensibly making germ-line edits to our cultural DNA, though the illusoriness of free will prevents us from taking such change quite as seriously as we should. 
<br></br><br></br>
One of the most deeply felt aversions to the notion of human enhancement that hinges on the concept of authenticity, is the idea that, left to our own devices, we will eventually make of ourselves things that are, in some sense, utterly divorced from the ultimate/larger/underlying Reality of things. This intuition is captured perfectly in Brave New World with the use of the drug Soma, a kind of chemical ecstasy that everyone consumes ostensibly all the time, that colours their every experience. Everything, when on Soma, is gravy as. No matter how dark the person’s experience is, conceptually, experientially it’s bliss. The death of a loved one, for instance: so long as enough Soma’s in the person’s system, the emotional response to losing one’s closest relationship would be indistinguishable from the experience of the most mind-blowing sex. Everything is Bliss.
<br></br><br></br>
On the surface of things, this sounds great - utopian. And yet, something about it scares the shit out of us. This was of course part of Huxley’s genius, his ability to illuminate the blurriness between utopia and dystopia. When asked what the defining quality of a utopia would be, the most obvious response is, “Well, everyone should feel good all the time”. That is, a world free of suffering. If there was much suffering, by definition, such a world would be disqualified from the label of utopia. However, our response to Brave New World challenges this assumption. There’s more to a good life than ecstasy, at least we all seem to think. 
<br></br><br></br>
There’s a couple of reasons why this might be the case. Firstly, there’s the fact that ecstasy - of the sort induced by Soma in BNW, and in our world, literal ecstasy - represents only one positive stand of mind, one flavour of well-being, among innumerable others. Part of why we take issue with the constant, indiscriminate and universal consumption of Soma is that it would mean we are opting for one positive state of being, to the exclusion of all the others. We want to feel good, sure. But we also want to feel good in all the ways. Though we might prefer one flavour of ice-cream, we want others from time-to-time, too. Irrespective of how much you like vanilla ice-cream, a world where vanilla ice-cream is the only source of food is a most terrifying kind of hell. 
<br></br><br></br>
But there’s another reason. That is, that it’s Good, in the moral sense, to be connected to the actual state of things, for our thoughts and emotions to track the solid ground of Reality. Even if it means occasional suffering, we should nevertheless prefer a world wherein our experience is honest to, and accords with, the Truth of things. To experience emotions and thoughts that are less-than-faithul to said Truth is to live a life that is fundamentally false, dishonest, inauthentic. Such a life, it goes, would be Bad. 
<br></br><br></br>
Such a life would indeed be Bad. And not only because of its lack of authenticity, although that provides some grounds for wanting to avoid such an existence. More importantly, though, we want our experience to be faithful to Reality because without such an alignment, it’s ostensibly impossible to flourish in the broadest sense possible. When our experience is commensurate with the Truth, we are best able to successfully navigate our circumstances, to make decisions and take actions that maximise our future well-being. When we suffer - not always but very often - we are gaining valuable information about our relationship to the world. Information that then informs our behaviour. Thoughts and emotions are valuable sense data when they are grounded in the underlying facts of the matter, misleading and destructive when they’re not. Our cognition is like a GPS system of sorts, and like our GPS, we want our cognition to map/reflect the actual, objective state of things. 
<br></br><br></br>
Take the trivial example of physical pain. Say we suddenly begin to experience some form of pain around our chest and shoulder area. If our response to that situation is, “Fuck, that doesn’t feel so good” we are rather likely to do something about it. Depending on our age and knowledge, we might draw the connection between our pain and a heart-attack. That thought might in turn lead to our calling an ambulance. If the pain was in fact the result of a heart-attack, then our experience being faithful to the actual goings-on of things could likely save our lives and thus preserve whatever future well-being we might experience. If, however, we are artificially in a constant state of pleasure, we would perhaps never know that we were having a heart-attack and therefore never make the call. In such a case, we are far more likely to keel over. Given all the well-being we would lose out on, that would indeed be Bad. 
<br></br><br></br>
One could, of course, look to make the opposite argument. Barring perhaps the example of physical pain, being disconnected from Reality might, at least in some instances, result in far greater well-being than a truly faithful relationship with ground truth. In support of this claim, one might point to the worldly successes of certain dreamers, do-ers, change-makers, “visionaries”. Among others, Kanye comes to mind. Visionaries, they could argue, are successful precisely because they neglect Reality and instead make their own, that their prosperity is the result of their dogged unwillingness to accept the notion of Truth, their capacity to bend the “facts of the matter” into “facts of their own”. 
<br></br><br></br>
Such an argument would nevertheless be mistaken. Firstly, we must distinguish between worldly success and well-being. Though visionaries of the sort our current culture tends to admire/worship/celebrate may achieve much of the former, acquisition of the latter doesn’t appear to be directly linked. Indeed, the two are very much separate things. People who achieve great deals of worldly success, as a product of their seemingly flexible relationship with the Truth, do not by necessity also achieve high levels of well-being. Thus even if we concede that a distorted or unfaithful perception of Reality may, in some cases, be conducive to the conventional notion of success, there is very little to suggest that such a perception leads to heightened levels of well-being. Quite the opposite, the evidence strongly suggests that maladjustment to Reality and well-being very much work against each other. Purely from an everyday experience standpoint, it’s more often than not the case that when we are experiencing some form of psychological suffering, even just reframing that suffering in a more expansive/enlightened/honest light tends to resolve the suffering. The same goes for physical pain. Consider exercise. If our understanding/framing of the experience of exercise wasn’t faithful to the actual facts of the matter - that exercise is good for us, that the pain is a sign of perfectly natural and indeed positive physiological processes etc. - we would find it insufferable. Because our perception is generally in accordance with the underlying Reality, however, we can tolerate it. Some even find it immensely pleasurable. Taking this line of argument even further, there’s even a strong - and indeed empirically verifiable - case to be made that a truly veridical perception of things is itself the most compelling flavour of well-being. If we regard Enlightenment as the state of mind most commensurate with the reality of the human condition, the most “true” state of awareness, then given the inherent pleasure of said state of mind, accurate perception and well-being would thus not only be consonant but actually synonymous. The difference between pleasure of the variety induced by Soma and the pleasure of Enlightenment, however, is that the pleasure of Soma excludes other varieties of experience, whereas Enlightenment is consistent with almost every conscious experience, as it’s not so much an experience as a quality of experience that can be discovered within - or on the very surface of - all experiences. We’ll return to this claim later. 
<br></br><br></br>
Though it’s tempting to ascribe the worldly success of certain individuals to the fictionality of their Reality, often, what might seem to be the product of magical thinking - a shaky relationship with the Truth - is little more than an unconventional interpretation of it. In other words, it’s not the quality of their sense data that leads such individuals to take action we might view as crazy, arrogant or egomaniacal, but rather a different take on what the implications of those sense data are. Just because something is extraordinarily unlikely or difficult, for instance, it does not follow that we shouldn’t at least go for it. It would be magical thinking to believe that the statistical probability of making the NBA if you’re 5’6” is high, but it’s by no means magical thinking to dedicate your life to defying the odds. Indeed, if it’s a burning desire you have, it might be perfectly rational behaviour. More often than not, we are best served by the Truth. Knowledge is power, after all. It assists us in our efforts in the world. Knowing all the ways we might fail helps us hedge against them, it helps make the “impossible” possible. 
<br></br><br></br>

      </p>
      </div>
    </main>
    <Footer nextTitle="Unintended Consequences" nextPage="/consequences"/>
    </>
  );
}

export default Authenticity;
