import React from 'react';
import styles from './Background.module.css'
import Footer from '../components/Footer/Footer';

function Consensus() {
  return (
    <>
    <main className={styles.container}>
        <div className={styles.box}>
        <h3 className={styles.preface}>The Historical Background</h3>
      <p className={styles.content}>
      What if we had the tools to fashion ourselves anew, according to our desires, to make ourselves in our own image? Would we make of ourselves something superior, in some ultimate sense, to what we are at present? Or, would we instead end up as some perverted Frankenstenian-type creation, with three heads two toes and belly buttons that can’t decide whether they’re ‘innies’ our ‘outties’, as per the concerns of many? Would it be a boon to the world, in other words, or its end as we care to know it? Questions, such as these, that were once purely abstract speculations, have become increasingly pragmatic considerations over recent years, as the means by which we alter ourselves grow increasingly powerful and precise. Most significantly, the development of ‘genetic engineering’ technologies have brought the subject of our organismic future into closer examination. To what extent, if at all, should we intervene in the handiwork of Nature? we find ourselves asking. Is it ‘right’ to ‘edit’ What We Are? If not, is it even possible to stop what’s already well underway? Is the future inevitable? Far from academic, how we answer these questions will define Who and What we become, and the world we create - or destroy. <br></br><br></br>

We humans make change. To our environments, to ourselves. Change is what we do, it’s inexorable from our identity as sentient, living-breathing things. It’s therefore not without a juicy sliver of irony that, some couple hundred thousands years into a history defined by change - much of which was at least ‘intentional-ish’ - we find ourselves asking whether it’s in fact a good idea. Whether we should change ourselves is thus, on some level, akin to asking whether the sky should be blue - largely irrelevant. The essential fact is, the sky is blue (at least some of the time) and will continue to be blue, whether or not we think it ought to be. And so it is with us and our propensity for change. Where the analogy between changing ourselves and the colour of the sky breaks (at least partially), is of course in our ability to intervene, according to our judgment. If we think we ought to change, we can change - at least within certain bounds. It’s one of the things that make us so cool. The sky, on the other hand, will simply keep on keeping blue. We can therefore understand our growing concern/anxiety over the ethics of ‘engineering ourselves’ as proportionately reflecting our ability to do so. With great power, as Spiderman’s dad once said, comes great responsibility. It’s this power, and the burden of its responsibility, that we are beginning to reckon with. <br></br><br></br>

So we’ve been making change since day one, right. That’s not new. What is, then? For starters, the rate of change is definitely unprecedented. While there’s some argument over whether innovation has recently stalled, if you take a broader view, it’s clear that the overarching trend is towards an increasing pace of change, novelty. History is, in some sense, speeding up. Nothing happened for the longest time, and then language and the agricultural revolution and writing and then the scientific revolution and then the industrial revolution and the digital revolution. Now there’s so many revolutions it’s hard to keep track of. It’s practically revolution city over here on earth. Shit’s getting weirder by the minute, and the minutes are getting faster by the second - or something. You get me. <br></br><br></br>


Why have things sped up? There are many ways to cut at this question. However, the most parsimonious explanation centres around the ‘metaphysical’ nature of technology. See, technology is fundamentally an agent of change. And change, by its nature, begets more change. Change makes change, and change also makes change. That’s kinda how it works. Thus, as technology becomes increasingly powerful, change becomes increasingly rapid. It’s a feedback loop, a snowball effect. Technology begets more technology which in turn begets more technology and so on ad nauseam. Now we’re snowballing.
<br></br><br></br> 

Although there’s long been concerns about how our modulating the environment will affect who we are, it’s not until relatively recently that we’ve become concerned with modulating or engineering ourselves directly. Since the rise of the biomedical model of medicine, we’ve been engaging, at least somewhat, with what it means to intervene in the human condition. Moreover, a growing understanding of the physiology of our brains has dramatically altered our conception of ourselves, and increasingly powerful chemical tools for manipulating our neurophysiology - and therefore, our identity, our selfhood - have called into question what is proper and legitimate, versus what’s stupid/unethical. Above all else, however, it was the discovery of the gene and the concept of heredity that brought the subject of human enhancement to the fore of the human dialogue. 
<br></br><br></br>

In the 19th century, there was a monk who had an interest in all things scientific. His name was Gregor Mendel. He farmed peas, for science. By breeding different varieties of peas together, he noticed a number of things. Most consequently, he observed that the traits or attributes of his pea plants were passed on from one generation to the next. Tall pea plants would breed tall pea plants, ones with certain kinds of flowers, certain kinds of flowers. Curiously, even when he bred tall plants with shorter ones, he noticed that the traits of the tall plants would occasionally be transferred in fill - ‘true’ - to the subsequent generation of pea plants with a kind of mathematical consistency, as in every so often. Rather than being the average of the two parent pea plants, the pea plant children would sometimes be tall, sometimes short. From this, Mendel surmised that their must be some essential, non-dilutable ‘thing’ being transmitted across generations of peas. There must be a thing for tallness, he realised, another for floweriness. A thing for everything. Sometimes, the thing from mother pea would appear in its offspring, sometimes the thing from the other father pea. <br></br><br></br>

Mendel of course discovered something big. We are made of genes, genes that we inherit from our parents. Although today we take this idea for granted, as a trite fact of our existence, at the time it was by no means self-evident. Indeed, we had no idea how we acquired our stuffs. As such, you would expect that Mendel’s findings - published in 1865 - would have taken the world by storm. But for poor old Mendel, that’s not how it played out. On the contrary, his work was published to the sound of crickets. Without Twitter, Mendel’s work remained in obscurity for decades. It wasn’t until around 1900 that his work was finally picked up by the scientific community. <br></br><br></br>

Around the same time Mendel was farming peas, another dude was looking at birds in the Galapagos Islands (who’d you rather be LOL). His name was Darwin. Charles Darwin. In-between sun-baking and swimming (presumably), Darwin was collecting exotic species, for science. At the time, the work Darwin was doing was quintessential biology - what we today call taxonomy, the classification of flora and fauna. Back to the birds, though. Across the islands, Darwin observed a bunch of different types of finch. Some with larger beaks, different coloured feathers etc. He found this curious. Why should there be so many similar, yet distinct varieties of the same bird? Why should God make so many species of virtually the same thing? That would be ridiculous, he reckoned. Excessive. Perhaps, he hypothesised, they weren’t different species of bird at all. Maybe they’re all ‘variations’ of the same species of finch. HUGE.<br></br><br></br>

During his voyage aboard the HMS Beagle, Darwin was of course laying the foundations of his/the theory of Evolution, which he would later publish (in 1859) as ‘On the Origin of Species’. Where Darwin and Mendel’s work converged, some 60 years later, was in the mechanism by which evolution takes place. For evolution to do its thing, for changes to be transmitted from generation to generation, Darwin realised, these changes must be instantiated or embodied in some physical thing. There had to be a physical mechanism, in other words, by which variation could occur and be transmitted across generational lines. For this, Darwin posited the existence of  “gemmules” - little particles that the body would emit and send to the gonads so as to be transferred to offspring. Although it was a cute and not entirely false idea, it wasn’t fully on the money, either. Enter, Mendel. What Mendel was studying, remember, were the ‘laws of inheritance’. However, traits of any kind were passed down from parent to offspring must be the same mechanism by which evolution works its magic. <br></br><br></br>

Eventually, the link between the two’s work was made. We are made of stuffs, stuffs we inherit from our parents, stuffs that evolve. The stuffs are genes, the means by which we inherit them the magic of sperm and egg doing their thing, and the ‘evolve’ piece a process of ‘natural selection’. This connection between heredity/genetics and evolution was finally drawn at the beginning of the 20th century, in what’s known as the “Modern Synthesis”. <br></br><br></br>

The theory of evolution - with its notion of the ‘survival of the fittest’ - was (and remains) a powerful idea. However, unlike Mendel’s work, which remained in obscurity for decades, the significance of Darwin’s work was almost immediately recognised. With the understanding that there are individual units of our ‘individualness’ - genes - and a mechanism by which those units are selected for, came the idea that we could take our destiny into our own hands - through selective breeding. Like farming peas, we could farm the human population so that the ‘fittest’ were all there was. By breeding only the best stock, we could ostensibly speed up the process of evolution. And so was born the concept of ‘eugenics’.
<br></br><br></br>
The term was coined by one Francis Galton, an English polymath interested in, among other things, the concept of ‘human improvement’. Galton was one of the first to fully grock the implications of Darwin’s theory. Not only did it undermine creationist theology, he realised, it also implied the possibility of intentionally guiding the future of our species. “We cannot doubt,” he wrote, “the existence of a great power ready to hand and capable of being directed with vast benefit as soon as we have learned to understand and apply it.” <br></br><br></br>

In 1883, Galton published a provocative book - Inquiries into Human Faculty and Its Development - in which he laid out a strategic plan for the improvement of the human race. In it, Galton proposed that by mimicking the mechanism of natural selection, we could intervene in the development of human civilisation, and, at least in principle, greatly improve it. Unnatural selection, he argued, was a logical and desirable complement to natural selection. He coined the term eugenics to denote his agenda, ‘the science of improving stock,’ as he put it, “to give the more suitable races or strains of blood a better chance of prevailing speedily over the less suitable.” <br></br><br></br>

The initial idea for the eugenics program was to breed the ‘best with the best’. Arranged marriages were the proposed mechanism. Galton, for one, fantasised about a world where a record of the best traits in the best families could be maintained by society - generating a ‘human studbook’ of a kind. Men and women, in such a world, would be selected from this record, according to their compatibility, and bred to produce the best, ‘fittest’ offspring. However, for reasons both practical and quasi-scientific, it was decided that such a ‘positive’ eugenics program was untenable. Instead of selecting for society’s best, the way to go - it was held - was selection against the worst; “the selective elimination of the weak”. While there was some concern expressed RE the scientific legitimacy of such a program, not to mention moral implications, others, such as the British novelist H.G. Wells, were convinced of its urgent necessity. Having imagined, in his 1895 book The Time Machine, a society literally divided along racial lines, Wells was convinced that the desire to manipulate heredity in order to create a “fitter society” was a legitimate and indeed positive one. However, he also believed that selective inbreeding via marriage, as was proposed, would likely produce weaker and ultimately inferior generations. Thus he argued, “It is in the sterilisation of failure, and not in the selection of successes for breeding, that the possibility of an improvement of the human stock lies.”<br></br><br></br>

From here, it’s easy to see how you get Hitler and Nazi Germany. Believe it or not, though, Hitler and the Nazi’s were truly convinced that what they were doing was entirely scientific. Indeed, Nazism, the biologist Fritz Lenz once said, is nothing more than “applied biology”. Of course, Nazism wasn’t the least bit scientific - it was racial genocide, the most grotesque display of (un)humanity. Our darkest hour. Though the Nazi program is certainly the most horrific eugenics campaign in human history, it was not the first. Lesser known, the US had begun a similar - albeit less murderous - experiment some couple of decades earlier. Throughout the early decades of the 20th century, stoked by the same fears of racial degeneration as Galton and his friends across the Atlantic, pro-eugenic sentiment was gaining steam. The leader of the American eugenics campaign was a fellow by the name of Charles Davenport, a Harvard-educated zoologist, who had founded a eugenics-focused research centre and laboratory - the Eugenics Record Office - in 1910. The following year, Davenport published a book that would become the movement’s bible - Heredity in Relation to Eugenics. As a matter of fact, it was also widely assigned as a textbook of genetics in colleges across the country. <br></br><br></br>

By 1912, following the first international Conference on Eugenics in London, eugenics was officially a full-fledged movement. In the US, the American Breeders’ Association had been established in order to eliminate “defective strains” of people, through the creation of confinement centres, “colonies” for the genetically unfit. Committees had been formed to consider sterilisation for inferior/unfit men and women - epileptics, criminals, deaf-mutes, the feebleminded, those with dodgy eyes, bone deformities, dwarfism, schizophrenia, manic depression, or insanity. “Nearly ten percent of the total population… are of inferior blood,” claimed the president of the association, Bleeker Van Wagenen, adding, “they are totally unfitted to become the parents of useful citizens… In eight of the states of the Union, there are laws authorising or requiring sterilisation.” In “Pennsylvania, Kansas, Idaho, Virginia… there have been sterilised a considerable number of individuals… Many thousands of sterilisation operations have been performed by surgeons in both private and institutional practice.” <br></br><br></br>

Buck vs Bell, a landmark Supreme Court case, laid the precedent for sterilisation, providing legal grounds for the involuntary sterilisation of certain kinds of genetically “inferior” peoples. Writing the 8-1 majority opinion, Oliver Wendell Holmes Jr. reasoned, “It is better for all the world, if instead of waiting to execute degenerate offspring for crime, or to let them starve for their imbecility, society can prevent those who are manifestly unfit from continuing their kind. The principle that sustains compulsory vaccination is broad enough to cover cutting the Fallopian tubes.” What ensued was a governmentally-sanctioned eugenics program that lasted decades. All told, approximately 70,000 Americans were forcibly - and legally - sterilised. While that number pales in comparison to the 6 million Jews (and countless others) that were exterminated in camps and gas chambers during the Holocaust, it demonstrates that evil isn’t always as flagrant as we tend to think. Indeed, what makes evil so effective is not its flagrancy but its subtlety, its ability to masquerade as justice or righteousness and thus hide in plain view.<br></br><br></br>

The purpose of providing this potted history of eugenics is to set the scene for the present historical moment, to establish the context in which the current conversation concerning human enhancement takes place, to illuminate the cause of our collective fears and anxieties. Most importantly, however, it’s to remind us of the fact that real lives are at stake here, that what we consider to be ethical and just, as it pertains to engineering or enhancing ourselves, will have far-reaching real-world consequences - as it always has. It’s therefore up to us to ensure the determinations we make don’t repeat the moral failures of our past, that the consequences of our decisions are those we can live with - ideally, those that posterity comes to celebrate. <br></br><br></br>

      </p>
      </div>
    </main>
    <Footer nextTitle="Treatment Vs Enhancement" nextPage="/treatment"/>
    </>
  );
}

export default Consensus;
