import React from 'react';
import styles from './Positive.module.css'
import Footer from '../components/Footer/Footer';

function Positive() {
  return (
    <>
    <main className={styles.container}>
        <div className={styles.box}>
        <h3 className={styles.preface}>Towards a Positive Conception of Health</h3>
      <p className={styles.content}>
      Health as the absence of sickness and health as homeostasis are both what’s known as ‘naturalist’ conceptions of health. That is, they’re both based on the premise that health can be entirely understood in terms of empirical facts about human physiology; that health is completely and solely within the purview of biological science. Health as the absence of sickness is also a fundamentally negative conception of health. That is, health is what you get when certain undesirable conditions do not exist. Health is what you get when there’s no sickness. Health as homeostasis, while not a negative conception in the same way health as the absence of sickness is, nevertheless implicitly eschews any kind of positive standards of health, beyond of course those that pertain to homeostasis. As we saw, homeostasis provides no defensible basis for arguing that to have vision is healthier than to not. Naturalism (also known as neutralism) is ‘value-free’, in other words. This is to be contrasted with normativism, which in this context, is the position that concepts such as health and disease are not only reflections of certain underlying biological realities, but functions of our values. According to the normativist (also known as ‘constructivist’) view, defining health not only involves establishing certain facts about human physiology, but also “involves shared judgments about what we value and what we want to be able to do.” In other words, the normativist conception of health should take into account both what it is to be human and what it ought to be. Thus, in contrast to the naturalist or neutralist position, the normativist conception of health is a fundamentally positive one. That is, it’s based on a set of positive standards regarding what it means to be healthy. As I’ll argue, normativism is the superior of the two positions — philosophically speaking — and pragmatically, the most aligned with how we should think about — and act on — our own individual health.<br></br><br></br>

The difference between homeostasis and health is that the former is a purely biological phenomenon, a value-independent physical reality, whereas the latter is what we may refer to as a ‘bio-cultural’ concept, a phenomenon that emerges at the nexus of biological facts and human values. Contrary to the naturalist view, health cannot be reduced to biology, though it is of course grounded in it. To illuminate this point, consider mental health. What we define as psychologically healthy or otherwise is just as bound up in cultural values and expectations as it is physiology. It is deemed unhealthy, for instance, to have a short attention span or to be ‘hyperactive’. We diagnose it as ADHD and prescribe rather powerful drugs to treat it. But in what sense is this unhealthy? Like blindnesss, a short attention span doesn’t imply physiological disorder or imbalance. There is no wholly objective standard by which to support the claim that such a trait is necessarily unhealthy. Indeed it’s only considered unhealthy and treated as an illness for the fact that we value behaviour that conforms to social and cultural aims and values, and dislike behaviour that diverges from them. In the case of ADHD, we label it an illness because it clashes with our present system of education, our values of order and obedience. We value, as a society, good boys and girls who do what they’re told, while we punish and alienate those who don’t. Biologically speaking, there is nothing intrinsically unhealthy about a short attention span or an abundance of uncontainable energy. In one context — school — such traits are maladaptive. In another context, however, they could be highly well-adapted.<br></br><br></br>

There’s innumerable examples of this kind of thing; a trait — or set of traits — that are adaptive in one context and maladaptive in another. Almost all of what makes modernity so challenging, in fact, can be traced back to layers or dimensions of our psychology that were once highly advantageous — serving to keep us alive — that are now extremely antagonistic to our individual and collective well-being. Our tribal instinct, for example, was once the difference between life and death. In the context of a world where one was at constant war with one’s neighbours, when an unfamiliar face most often meant an unfriendly face, a propensity to harbour ill-will and animosity — suspicion at the very least — towards the world outside of one’s tribe was perfectly sensible — healthy, even. Fierce tribal loyalty and out-group resentment reflects what was a response to a certain reality of human life at the time. Today, however, in a world where someone from the other side of the river and over the hill is highly unlikely to plunder one’s village or enslave one’s people, tribalism is a highly problematic piece of software to be running. It’s not the end of the world when it’s confined to the domain of sport, but it’s quite possibly the end of the world when it seeps into our politics, informing how we view relations with different people from different places.<br></br><br></br>

Naturalistically, that is, without appealing to values, there’s no grounds on which to label either ADHD or tribalism unhealthy. They’re both simply evolved traits that were once — and in some contexts perhaps still are — perfectly adaptive. If one employs values in their conception of health, however, one may respectably argue that both ADHD and tribalism are — generally speaking — unhealthy and should be treated as such. That’s not to say that a value-dependent conception of health must necessarily assert that both of these traits are unhealthy. Indeed, depending on the particular values employed in such a conception, one might argue the opposite: that they’re both perfectly healthy qualities — ideal, even. This is of course the very problem with a value-laden, positive conception of health, and thus the most common objection to it. How could we possibly have a meaningful, universal, objective conception of health — so the argument goes — if such a conception were to include values, values that are inherently subjective, relative, contextual? While this objection may at first appear to be a devastating argument against a positive conception of health, as I’ll argue, it’s not.<br></br><br></br>

As we saw with well-being, values are intimately connected to facts; facts about the world, facts about ourselves, our brains. The two classes of knowledge that values and facts represent — philosophical and scientific, subjective and objective — are not separated, as it’s popularly thought, by some kind of impassable epistemic chasm. With Reason, we can bridge them. Facts about the relation between the human brain and the world — facts about what is — can and should inform us as to how things ought to be. The fact that the interaction between our brains and the world results in subjective experience — consciousness, qualia — combined with the fact that there are things we can do to improve the qualitative nature of experience, serves as a scientific, objective rationale for pursuing — that is, valuing — well-being, and mitigating — disvaluing — suffering. Such a value is not merely arbitrary, relative or contextual. It’s not divorced from the world of facts; it’s steeped in it, and inseparable from it. And just because values are not objective in the same fashion as the laws of physics, it does not follow that we are obliged to take everyone’s conception of values equally serious, in the same way that we’re not obliged to take every theory of gravitation equally serious. Permitting values into our conception of things, in other words, is not to invariably permit all opinions, to do away with any kind of objectivity and thus surrender to epistemic relativism. Contrary to this concern, we can in fact be right and wrong about questions of right and wrong. Values are more than mere smoke and mirrors, as it were.<br></br><br></br>

In the same way that a science of well-being or a science of morality is a real and achievable ideal, and not a mere contradiction in terms, so too is a rational, value-inclusive conception of health. We can indeed include values into our picture of health, without sacrificing our intellectual self-respect. So the question is not ‘Should we include values into our conception of health?’, for values should and already do inform how we conceive of health, but rather, ‘What values should we include?’ To that let’s now turn.<br></br><br></br>

Now, if we’re intent on including values in our conception of health, as I say we should be, we must then ask ourselves, ‘which values?’ We can’t simply argue that all that is good is healthy, while all that is bad is otherwise, even if what we end up with bears a striking resemblance to this claim. No, we’re doing philosophy here — very serious philosophy — so we must be a touch more rigorous. Given the ground we’ve already covered, it would seem to make sense — at least it seems to me — to start with well-being. And since I’m the one writing this thing, that’s what we shall do…
<br></br><br></br>



      </p>
      </div>
    </main>
    <Footer nextTitle="Health as Well-being" nextPage="/wellbeing"/>
    </>
  );
}

export default Positive;
