import React from 'react';
import styles from './Prevention.module.css'
import Footer from '../components/Footer/Footer';

function Prevention() {
  return (
    <>
    <main className={styles.container}>
        <div className={styles.box}>
        <h3 className={styles.preface}>Prevention As Research Paradigm</h3>
      <p className={styles.content}>
      While prevention rather than treatment should, on purely pragmatic grounds, be the aim from both an individual, as well as public health perspective, it also serves as a viable research paradigm. As we saw, part of the reason effective, targeted treatment is so notoriously difficult is the sheer complexity of biological systems and the subsequent opaqueness of the causal dynamics that underpin disease (and biological functioning generally). Thus if the ability to reliably intervene in disease states requires our understanding the entire array of physiological processes that mediate them, such an ability may, perhaps, never materialise. If, however, there happens to be a small (or at least smaller) number of ‘higher-order’ processes that regulate the function of the majority of other processes, then perhaps all we would require in order to intervene in all or most disease is a comprehensive understanding of those few higher-order ones. If, for instance, all disease was the result of an imbalance of the four humors - à la Galen - then, so long as we understood how to modulate their balance, we would therefore have mastery over every ailment under the sun. Alas, a return to humorism is unlikely to prove productive. Seductive as the idea is, it’s not the most fruitful framework for understanding what we are. That said, there is good reason to believe that there’s such higher-order processes, if not literally resembling the humors at least conceptually similar, that are implicated in almost every chronic disease. Take ageing for instance. Age is the single greatest risk factor for almost every chronic disease. The older you are, the more at risk you are of having some debilitating condition. Age is also the single greatest risk factor for death. The older you are, the more likely you are to die. So whatever causes us to age, also causes us to get sick and die. 
<br></br><br></br>

Thus ageing can - in some sense - be viewed as the ‘root’ cause of a great majority of diseases, certainly those which most afflict modern society. Rather than pursuing a comprehensive, mechanistic understanding of the myriad processes that underly all of the manifestations of ageing, it therefore stands to reason that we would be better off going after ageing itself. To the degree that understanding the processes that govern ageing requires understanding lower-level mechanisms, at say the molecular level, it should be embraced. Understanding mechanisms for the sake of understanding mechanisms, however, should be avoided. For given the scale of what there is to know about biological systems, there needs to be at least some self-imposed constraints for efficiently coordinating our research efforts.
<br></br><br></br>

Over recent years, this ageing-first approach to disease prevention has become increasingly popular. While ageing research has historically been viewed as a somewhat kooky scientific interest, it has increasingly come to be seen as a legitimate field of investigation. Recent interest in the field comes off the back of, among other things, calls for ageing to be viewed as a disease in itself. Critics of longevity science argue that ageing is a not a disease as it’s an entirely ‘natural and universal process,’ but as is frequently pointed out, so too are many - indeed all - other diseases. This speaks, in part, to the arbitrariness of nosology (the classification of diseases) and the social/cultural factors that influence our perception of what constitutes disease. In any event, recent efforts to uncover the causes of ageing have led to the discovery of a number of organism-wide processes associated with ageing, such as cellular senescence and DNA damage, as well as an ability to effectively mediate those processes in animal models. If nothing else, the view that ageing is indeed a disease, is therefore proven to have considerable ‘cash-value’. 
<br></br><br></br>
Whatever the physiological processes that drive ageing, we know that ageing is fundamentally the result of the infamous second law of thermodynamics. That is, the tendency for things to go to shit over time. That life seemingly defies this most morbid of laws is, as Schrodinger identified, one of its hallmarks. By leveraging what he termed ‘negative entropy’ (or negentropy for short), life is able to stave off the second law - at least for a time. Food, air and water are the quintessential examples of negative entropy. However, all other things that promote health can also be understood abstractly as the same. Just as one’s health bar in a video game can be replenished by stumbling upon a care package or pressing buttons in a particular sequence, by ‘feeding on the environment’, so too can we replenish our own - by reversing the arrow of entropy. How exactly life accomplishes this miraculous feat was of great interest to Schrodinger, one of the central questions posed in ‘What is Life?’, and ultimately one of the reasons he posited the existence of ‘new laws of physics’ that might help explain the mysterium tremendum that is life. In all likelihood, what was perplexing to Schrodinger was not new laws of physics, necessarily, but rather the emergent, complex behaviour that comparatively ‘simple’ low-level laws, if not create, at least enable. What he was pointing to, in other words, was not new laws of physics at all, but the laws of biology. Whether you choose to call it negative entropy or free energy or information, that life can harness stuff from its spatiotemporal environment in order to regulate itself, reduce internal entropy, is key to its mystery. Understanding how this happens, what negative entropy ‘really is’, and ultimately, figuring out ways to artificially deploy it in vivo - our vivo - without fucking our shit up, is really the fundamental task of medical science. Somewhat ironically, after all this talk of complexity and emergence and non-reductionism, understanding ourselves may just require us to answer to certain basic features of the universe first. 
<br></br><br></br>

      </p>
      </div>
    </main>
    <Footer nextTitle="Reductionism In Biology" nextPage="/reductionism"/>
    </>
  );
}

export default Prevention;
