import React from 'react';
import styles from './Philosophy.module.css'

function Philosophy() {
  return (
    <main className={styles.container}>
        <div className={styles.box}>
        <h3 className={styles.preface}>What Is Philosophy?</h3>
      <p className={styles.content}>
      Philosophy is the pursuit of Knowledge. There are a number of ways to define philosophy, but this one - at least to my mind - comes as close to capturing its essence as any. Of course, it’s a rather loaded definition, for What is ‘Knowledge’? However, if we shelve that pickle for the moment and let our common sense understanding of Knowledge stand - as a synonym for 'justified true belief' - we have ourselves a perfectly fine definition of the philosophical enterprise.   <br></br><br></br>

We have been doing philosophy ever since we developed the capacity for thought. We are a truly philosophical species indeed, distinguished from the rest of known life - to the best of our Knowledge - by our propensity for reflection, inquiry, examination. The first instances of philosophical inquiry, we can well imagine, were inspired by the natural wonder of things. The starry heavens above, or the birth of a newborn, for example, might have served as the original source material for philosophical speculation, causing us to contemplate our place in the world, the Truth of our peculiar situation. For a long while - the great majority of its history in fact - philosophy was a fundamentally narrative tradition. That is, it took the form of stories intended to explain whatever gripped our imagination, whatever stimulated our philosophical appetite. The stars in the sky were the eyes of the Gods, red soil the blood of distant ancestors. Gradually, however, the scope of philosophy evolved beyond the most speculative form of metaphysics to include questions of every conceivable kind. Similarly, its method, the process by which we sought to understand the world - that is, attain Knowledge - evolved. <br></br><br></br>

The birth of modern philosophy, it’s generally regarded, was with the ancient Greeks some few thousand years ago. Names such as Socrates, Plato, Aristotle, and Democritus hailed as the founding fathers. Not to give the impression that nothing of significance happened until then, it surely did, but the Greeks are unique in that they did substantially more than anyone to define what philosophy is and how it should be done. Above all, it was the Greeks who brought a much-needed self-consciousness to the enterprise, an awareness of the pitfalls of its method and the ambiguity of its end. Beyond this kind of self-consciousness, the Greeks also made fundamental contributions to the method of philosophy itself, introducing a previously absent analytical rigour, with their emphasis on logic, rationality, mathematics and empirical observation. In effect, the Greeks sowed the seeds of both modern philosophy and science (the latter technically falling under the umbrella of the former), articulating and demonstrating how both ought to be done, thereby moving the needle of human understanding in major ways. It’s an incredible testament to the genius of the Greeks that there are very few significant philosophical questions - before or since - that they didn’t themselves pose. To this day, the works of such giants as Plato and Aristotle continue to be mined for insight and clarity on the big issues - such as the issue of Knowledge, as in ‘What is it?’ and ‘How is it possible?’ - that still confound us. What were the Greeks smoking? one might ask. As it happens, the question is rather, What were they drinking? Whatever it was, it was clearly good stuff. <br></br><br></br>

While the Greeks did much to widen the gaze of philosophy beyond the parochial or merely human, the central question of philosophy, then and until relatively recently, was the question of ‘How to live?’. To our modern minds, it’s an odd-sounding question, and any attempt at answering it, certainly on behalf of others, would seem to imply a degree of hubris that would inevitably undermine the answer, life being as ambiguous and open-ended as it is. But of course, it’s a question that we all wrestle with, as individuals, even if we don’t formulate the question so explicitly. Irrespective of how reflective we are with respect to our own lives, our actions in the world contain an implicit response to the question. Where we live, what we do for work, how we interact with others, when and whether we have kids, what we do in our spare time etc. The facts of our lives reflect, in addition to the vagaries of circumstance, our answers to this most perennial philosophical question. In other words, the question of how to live is, by virtue of our living, utterly inescapable. Like life itself, it is simply forced upon us. <br></br><br></br>

Around the birth of modern philosophy, when the foundation was being laid, as it were, philosophy was considered a highly practical affair, akin to something like the martial arts, with different schools teaching different philosophies, each principally concerned with question of how to live.  The first, and certainly most famous, philosophical school was Plato’s Academy. Located just outside the city walls of Athens, and infamously centred around a sacred grove of olive trees, the Academy is regarded as the first Western institution of higher education and is therefore attributed with greatly influencing our ‘modern’ system. Far from the stale and stuffy universities stitched together by ideology that we’ve come to know, however, the Academy was an eclectic community of intellectuals, united by a common passion for understanding and wisdom. Topics of study at the Academy ranged the full gamut, from poetry to politics  - and of course philosophy proper. Quite famously, a sign above the entrance of the Academy bore the inscription, “Let no-one ignorant of geometry enter here.” Suffice to say, mathematics was also part of the curriculum. <br></br><br></br>


      </p>
      </div>
    </main>
  );
}

export default Philosophy;
