import React from 'react';
import styles from './Welcome.module.css'

function Welcome() {
  return (
    <main className={styles.container}>
        <div className={styles.box}>
        <h3 className={styles.preface}>Welcome to Philosophy</h3>
      <p className={styles.content}>

      If you’re like most people (and most people are) you probably grapple with the question of how to live. And if you don’t, perhaps you ought to. For it’s the way in which we engage with this uniquely human question that determines the quality of our lives. Even if we don’t frame the question quite so explicitly, our every action represents an implicit response to it. Life - at least human life - is a fundamentally philosophical act. You see, contrary to the caricature of philosophy we tend to hold in mind - as something one does from the comfort of an armchair while stroking their long, grey beard - philosophy is in fact absolutely central to the human endeavour. Dealing, as it does, with the examination of values, beliefs and ideas - that is, the material of our lives - it is inexorable from our identity as human agents, a defining characteristic of What We Are. But even though we are philosophical creatures by nature, that does not mean we are all particularly good philosophers, nor does it mean that all “particularly good philosophers” are particularly good at life. It’s entirely possible, and indeed well demonstrated, that one may have a rather special affinity for contemplating abstract questions that pertain - however tangentially - to the nature of our existence, yet remain hopelessly incompetent at the art and science of living. <br></br> <br></br>

Philosophy, when it’s at its best, helps us to understand both ‘the way things are’ and how we can integrate this understanding into the fabric of our lives, so that we might get a little (or a lot) more out of them. When it’s at its worst, however, philosophy amounts to little more than intellectual masturbation; an activity that, however momentarily satisfying, adds hardly at all to the ultimate quality of our existence. In some sense, we’re currently living amidst a philosophical crisis. Having developed a reputation as an entirely intellectual exercise, bearing almost no direct relation to the ‘on-the-ground’ reality of human life, philosophy has become increasingly removed from the focus of the human project. As a society, focused as we are on the pursuit of “worldly success”, we’ve lost touch - almost entirely - with the ideals of the contemplative life. More than that, though, through our lack of contemplation, our lack of earnest engagement with the critical questions, we have enabled the creation of a world that is, for the most part, wholly antithetical to an examined life. The forces of the world - forces we have made manifest - now lead us not to Enlightenment, but rather towards cat videos and Tik-Toks.<br></br> <br></br>

Perhaps you’ve found yourself asking, Is there not more? Is there not more to life, for instance, than striving towards material prosperity? Is there not more to life than, say, satisfying one’s every fleeting impulse? Or in Drake’s case, is there not more to life than going on trips to Dubai, yachts on the fourth of July, or G-5’s soaring the skies? Whatever your particular predicament, it’s likely that you’ve wondered - if only during a rare moment of introspection - the same; that is, whether there isn’t more to this whole thing. Now maybe that’s as far as you took it. Or maybe you went one step further by asking, If so, what could it be? Happiness? Love? Enlightenment? All of the above? Now let’s assume there is more, how is one to get it? Practically speaking, what is one to do?<br></br> <br></br>

Welcome, my friends, to philosophy. <br></br> <br></br>

Whatever the colour of your eyes or the size of your feet, whether you identify as a he, she or, hell, even a unicorn, by virtue of your being thrown into this world, such questions are quite literally forced upon you. What defines our lives, however, is not whether such questions merely suggest themselves to us - although that’s a good start - but rather our response to them - whether we confront them, head on, or merely cower away and defer to the opinions of others.<br></br> <br></br>

The thing about modern life - and you might’ve noticed this - is that it’s hard, non-obvious, complicated. Having drifted worlds away from an environment that we’re biologically and psychologically well-adapted to, without some guiding set of principles, or heuristics, it’s damn near impossible to live good - as in, really good. Our instincts, evolved for hunting prey and defending against predators as they have, are much less suited to helping us navigate our modern predicaments than they were the plains of Africa - our motherland. Or perhaps that’s not it at all. Perhaps it’s merely the fact that we’ve become so abstracted from our instincts that we’re having such a hard time. In either case, it’s clear that philosophy is needed now more than ever. Whether to augment our instincts, or help us rediscover them, the quality of our future - individually and collectively - is contingent upon our engagement - or lack of - with the fundamental questions of our lives - i.e. what does it mean to live well? and how? <br></br> <br></br>

Alongside our philosophical crisis - a crisis of values - we’re also dealing with a public health crisis - that is, a crisis of mind and body. Where the symptoms of the former are the materialist philosophy of life we’ve swallowed whole, which manifest in a variety of “sub-symptoms”, the symptoms of the public health crisis are similarly various, including - but not limited to - an obesity epidemic, an opioid crisis, a mental health epidemic, and, should we get a little more cosmic, a planetary-scale ecological disaster. In other words, it’s crises - not turtles* - all the way down. <br></br> <br></br>

While these twin crises are - at least on the surface - seemingly disparate, as I’ll attempt to persuade over the course of this thing, they are in fact deeply intertwined. Our lack of legitimate philosophising, I’ll argue, has led to a the proliferation of a value system that causes us to greatly undervalue health. Our lack of health, in turn, then renders us less inclined - certainly less able - to meaningfully engage with the questions that most concern our lives. Thus what we have given rise to is a kind of feedback loop of the most catastrophic variety, one where our values erode our health, and the erosion of our health then further degrades our values. A vicious spiral, to be sure. <br></br> <br></br>

Admittedly, there’s nothing all that interesting about the relationship between values and health, and certainly nothing revolutionary about the idea that one could negatively impact the other, or vice versa. What is interesting, however, is what a critical examination of the concept of health reveals - both in terms of What We Are, as organisms, and what we ought to value, as things that value other things. Even further, a “serious” investigation of health, as a philosophical concept and physical reality, provides insight into the very nature of the universe itself, this most bizarre Reality structure that we’re all embedded in. Health, as it happens, is a Pandora’s box. At first glance, it’s one thing - obvious in its importance, sure, but also trite for the same reason. Once you open the lid, however, it becomes something else and seemingly unending. What initially seems like something we ought to care about, at least to some degree, all of a sudden becomes something that encompasses all that we ought to care about. Health, I’ll be making the case, is not simply one value among all the others, but rather a “value superstructure”, a value above all values, so to speak. Everything we legitimately ought to value, we ought to value because of its relation to health - properly defined.  Of course, this claim - that “health is everything” - rests on a very particular definition of the word health, a definition I will expound and do my best to justify as reasonable. <br></br> <br></br>

Just as happiness and Enlightenment and “success” serve as philosophical orientations, ends towards which we might aim our lives, so too does health. In contrast to other such orientations, however, the concept of health provides both an abstract framework for thinking about what matters, as well as a practical guide by which we might attain or cultivate it - a guide that’s equally actionable at the level of our own lives as at the level of civilisation/society. Health, when it’s all said and done, provides the closest thing to an entirely comprehensive - dare I say, objective - “philosophy of life”, a North Star towards which we may reliably orient our lives - and the world - so as to realise our fullest potential as individual organisms, and a collective species. 
<br></br> <br></br>
For the above to make any sense at all, obviously health must extend beyond the mere physical, beyond big biceps or a glowing tan. In the “age of anxiety”, a moment in time where the concept of mental health is firmly embedded in our cultural vocabulary, that health might also include mental qualities is unlikely to elicit any push back or funny looks. However, the idea that health might encompass everything we are justified in valuing, every attribute that we ought to care about, will require much more convincing. Accordingly, in order to support this argument, there’s a lot of philosophical work or ‘table-setting’ that must be done - establishing definitions and what not. Fortunately, however, by necessity that “work” entails an exploration of some of the juiciest philosophical terrain there is. In getting to the heart of health, we must first adventure through the science and philosophy of consciousness, the basis of morality, the meaning of well-being, the concept of Truth, and the nature of Reality - to name a few. As such, the book serves as a kind journey across the landscape of philosophical ideas. Thus whether or not one comes to agree with the central thesis I like to think that there’s at least something of value here for everyone. <br></br> <br></br>

While the world could always do with quality philosophy, even putting aside the problems of our time, the present moment seems especially junctural and thus especially in need of good philosophy. For instance, as you’re reading this, our tools for modifying our condition - i.e. genetic engineering technologies - are growing increasingly powerful and sophisticated by the day. Although it’s still super early days in the overall scheme of the science/technology, as this trend continues - that is, the trend towards evermore powerful and precise biological interventions - we will at some point have on our hands - and to an extent, already do - God-like powers. With God-like powers, of course, come God-like decisions, God-like responsibilities. Before we make potentially irreversible decisions that will greatly affect the trajectory of the human enterprise, it would seem sensible that we should first get clear on what it is that we’re really doing here, what it is that we’re striving towards, what’s Good and what’s not. Unless we truly reckon with the great existential questions, and somehow find a way to converge - as a collective - on the right answers, it’s reasonable to expect that our technology will eventually be our undoing. For with the power to radically alter What We Are but without the wisdom do so intelligibly, it seems inevitable that this thing we’ve got going on would eventually unravel at the seams. <br></br> <br></br>

Lastly, as the late-great Wittgenstein said, “What can be said at all, can be said clearly; and whereof one cannot speak, thereof one must be silent”. It is in this vein that I’ve attempted to write this book. And although I’m sure I’ve fallen short of this ideal, at times, I’ve endeavoured to articulate the ideas that follow with as little pretence or unnecessary jargon as possible. After all, the book is written for understanding, not academia. It’s thus my hope that the book is as comprehensible to a first-time reader of philosophy as a bona-fide philosophy junky. Good philosophy, I hope to demonstrate, is not synonymous with impenetrable language or nauseating verbosity, but rather all the same virtues by which we measure the standard of any other form of human communication. Above all, though, good philosophy - I like to think - is philosophy that genuinely touches our lives, that which leaves us somehow different - indeed better - than we were before. With that… <br></br> <br></br>

      </p>
      </div>
    </main>
  );
}

export default Welcome;
